'use strict';
(() => {
const curriculum = window.NL_CURRICULUM;
const bank = window.NL_CASE_BANK;
const expansions = window.NL_CASE_EXPANSIONS || [];
const practice = window.NL_PRACTICE;
const atlas = window.NL_ATLAS;
const extras = window.NL_EXTRAS || {cards:[],finder:null};
const drills = extras.drills || [];
const drillById = Object.fromEntries(drills.map(d=>[d.id,d]));
const finder = extras.finder;
const diagramById = Object.fromEntries((atlas||[]).map(d=>[d.id,d]));
const BANK_REVISION = 2;
const APP_VERSION = '1.4.0';
const main = document.getElementById('main');
if (!curriculum || !bank || !practice || !atlas || !finder || expansions.length !== 2) {
  main.innerHTML = '<div class="empty-state"><h1>The study library could not load.</h1><p>Please close and reopen NeuroLocalize. If this continues, reinstall the APK.</p></div>';
  return;
}
const topics = [...curriculum.topics];
for (const t of extras.topics || []) { const i = topics.findIndex(x => x.id === t.after); topics.splice(i < 0 ? topics.length : i + 1, 0, t); }
const cases = [...bank.cases,...expansions.flatMap(e=>e.cases)], cards = [...curriculum.cards, ...extras.cards];
const sources = [...curriculum.sources, ...bank.sources,...expansions.flatMap(e=>e.sources)];
const topicById = Object.fromEntries(topics.map(x => [x.id, x]));
const caseById = Object.fromEntries(cases.map(x => [x.id, x]));
const cardById = Object.fromEntries(cards.map(x => [x.id, x]));
const sourceById = Object.fromEntries(sources.map(x => [x.id, x]));
const KEY = 'neurolocalize.study.v1';
const DAY = 86400000;
const iconPaths = {
 brain:'<path d="M12 4c-1-3-6-2-6 2-3-1-5 3-3 5-3 3-1 7 2 7 0 4 5 5 7 2M12 4c1-3 6-2 6 2 3-1 5 3 3 5 3 3 1 7-2 7 0 4-5 5-7 2V4M6 6c0 2 1 3 3 3M3 11c2-1 4 0 4 2M5 18c0-2 1-3 3-3M18 6c0 2-1 3-3 3M21 11c-2-1-4 0-4 2M19 18c0-2-1-3-3-3"/>',
 home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z"/>',
 book:'<path d="M12 5c-3-2-6-2-10-1v16c4-1 7-1 10 1 3-2 6-2 10-1V4c-4-1-7-1-10 1v16"/>',
 cases:'<rect x="4" y="5" width="16" height="17" rx="2"/><path d="M9 5V2h6v3M8 10h8M8 14h8M8 18h5"/>',
 cards:'<rect x="7" y="3" width="14" height="17" rx="2"/><path d="M4 6H3v15a1 1 0 0 0 1 1h13M11 8h6M11 12h6M11 16h3"/>',
 library:'<path d="M3 3h4v18H3zM10 3h4v18h-4zM17 4l4-1 4 17-4 1z" transform="translate(-1 0)"/>',
 settings:'<path d="m10 2-1 3-3 1-3-1-2 4 2 2v3l-2 2 2 4 3-1 3 1 1 3h4l1-3 3-1 3 1 2-4-2-2v-3l2-2-2-4-3 1-3-1-1-3z" transform="translate(1 0) scale(.92)"/><circle cx="12" cy="12" r="3"/>',
 arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',back:'<path d="M20 12H4m6-6-6 6 6 6"/>',chevron:'<path d="m9 5 7 7-7 7"/>',
 check:'<path d="m5 12 4 4L19 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',
 target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',
 shield:'<path d="M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6Z"/><path d="m8 12 3 3 5-6"/>',
 spark:'<path d="m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3z"/>',
 flame:'<path d="M12 2c4 6 8 8 8 13a8 8 0 0 1-16 0c0-3 2-7 5-9 0 4 1 5 2 5 2-3 2-6 1-9Z"/>',
 search:'<circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/>',
 bookmark:'<path d="M6 3h12v19l-6-4-6 4z"/>',
 external:'<path d="M14 3h7v7m-1-6L10 14M10 4H4a1 1 0 0 0-1 1v15a1 1 0 0 0 1 1h15a1 1 0 0 0 1-1v-6"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',
 activity:'<path d="M2 12h5l3-8 4 16 3-8h5"/>',
 layers:'<path d="m12 2 10 6-10 6L2 8zM2 12l10 6 10-6M2 16l10 6 10-6"/>',
 eye:'<path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',
 network:'<circle cx="12" cy="4" r="2"/><circle cx="4" cy="19" r="2"/><circle cx="20" cy="19" r="2"/><circle cx="12" cy="13" r="3"/><path d="M12 6v4m-2 5-4 3m8-3 4 3"/>',
 route:'<circle cx="5" cy="5" r="2"/><circle cx="19" cy="19" r="2"/><path d="M8 5h7a4 4 0 0 1 0 8H9a3 3 0 0 0 0 6h7"/>',
 leaf:'<path d="M20 3C5 2 1 8 5 15s15 3 15-12Z M4 21l11-12"/>',
 reset:'<path d="M3 10a9 9 0 1 1 0 6M3 3v7h7"/>',
 compass:'<circle cx="12" cy="12" r="9"/><path d="m15.5 8.5-2 5-5 2 2-5z"/>',
 grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
 prev:'<path d="m15 5-7 7 7 7"/>'
};
function icon(name, cls='') { return `<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[name] || iconPaths.brain}</svg>`; }
function esc(s) { return String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function dateKey(time=Date.now()) { const d=new Date(time); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
function blankState() { return {version:1,bankRevision:BANK_REVISION,read:{},bookmarks:{},attempts:[],reviews:{},days:{},drills:{},theme:'light',size:'normal',session:null}; }
let storageOK = true;
let editionUpdated = false;
function readState() {
  try {
    const raw=JSON.parse(localStorage.getItem(KEY) || 'null');
    const clean=blankState();
    if (!raw || typeof raw!=='object' || raw.version!==1) return clean;
    editionUpdated = raw.bankRevision !== BANK_REVISION;
    for(const t of topics) if(raw.read?.[t.id]===true) clean.read[t.id]=true;
    for(const c of cases) if(raw.bookmarks?.[c.id]===true) clean.bookmarks[c.id]=true;
    clean.attempts=Array.isArray(raw.attempts)?raw.attempts.filter(a=>a && caseById[a.caseId] && typeof a.key==='string' && Number.isFinite(a.time) && typeof a.correct==='boolean' && caseById[a.caseId].options.some(o=>o.id===a.answerId)).slice(-3000):[];
    for(const c of cards) {
      const r=raw.reviews?.[c.id];
      if(r && Number.isFinite(r.due) && Number.isFinite(r.interval) && r.interval>=0 && Number.isInteger(r.count) && r.count>=0) clean.reviews[c.id]={due:r.due,interval:Math.min(r.interval,365),count:r.count};
    }
    if(raw.days && typeof raw.days==='object') for(const [day,v] of Object.entries(raw.days)) if(/^\d{4}-\d{2}-\d{2}$/.test(day) && v && typeof v==='object') clean.days[day]={lessons:Math.max(0,Number(v.lessons)||0),cases:Math.max(0,Number(v.cases)||0),cards:Math.max(0,Number(v.cards)||0)};
    for(const d of drills){const r=raw.drills?.[d.id];if(r && Number.isFinite(r.best) && Number.isInteger(r.plays) && r.plays>0) clean.drills[d.id]={best:Math.max(0,Math.min(100,Math.round(r.best))),last:Math.max(0,Math.min(100,Math.round(Number(r.last)||0))),plays:r.plays};}
    if(['light','dark','system'].includes(raw.theme)) clean.theme=raw.theme;
    if(['normal','large'].includes(raw.size)) clean.size=raw.size;
    const s=raw.session;
    if(s && s.bankRevision===BANK_REVISION && typeof s.uid==='string' && ['tutor','exam'].includes(s.mode) && Array.isArray(s.ids) && s.ids.length>0 && s.ids.length<=cases.length && s.ids.every(id=>caseById[id]) && new Set(s.ids).size===s.ids.length && Number.isInteger(s.index) && s.index>=0 && s.index<s.ids.length && s.answers && typeof s.answers==='object') {
      const answers={};
      for(const id of s.ids) if(caseById[id].options.some(o=>o.id===s.answers[id])) answers[id]=s.answers[id];
      const firstUnanswered=s.ids.findIndex(id=>!answers[id]);
      clean.session={uid:s.uid,bankRevision:BANK_REVISION,mode:s.mode,ids:s.ids,index:firstUnanswered>=0&&firstUnanswered<s.index?firstUnanswered:s.index,answers,optionOrders:practice.restoreOptionOrders(s.ids,caseById,s.optionOrders),complete:s.complete===true && Object.keys(answers).length===s.ids.length};
    }
    return clean;
  } catch (_) {storageOK=false;return blankState();}
}
let state=readState();
let view='home', detailId=null, topicFilter='all', reviewFilter='all', difficultyFilter='all', taskFilter='all', onlySaved=false, query='', learnFilter='all';
let drill=null, atlasGroup='all', finderPicks=new Set(), currentDiagram=null, diagramZoom=1;
let selected=null, flash=null, pendingSession=null, toastTimer=null;
const sheet=document.getElementById('sheet');
const systemDark=window.matchMedia('(prefers-color-scheme: dark)');
function save() {try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch(_){storageOK=false;toast('Progress cannot be saved on this device. You can keep studying during this session.');}}
function applySettings(){document.documentElement.dataset.theme=state.theme==='system'?(systemDark.matches?'dark':'light'):state.theme;document.documentElement.dataset.size=state.size;}
if(systemDark.addEventListener) systemDark.addEventListener('change',applySettings);else if(systemDark.addListener) systemDark.addListener(applySettings);
function toast(text){const el=document.getElementById('toast');el.textContent=text;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,4600);}
function activity(kind){const day=dateKey();state.days[day] ||= {lessons:0,cases:0,cards:0};state.days[day][kind]++;}
function streak(){let n=0,d=new Date();if(!state.days[dateKey(d.getTime())]) d.setDate(d.getDate()-1);while(state.days[dateKey(d.getTime())]){n++;d.setDate(d.getDate()-1);}return n;}
function dueCards(){return cards.filter(c=>!state.reviews[c.id]||state.reviews[c.id].due<=Date.now());}
function latestAttempts(currentEdition=false){const latest={};for(const a of state.attempts)if(!currentEdition||a.bankRevision===BANK_REVISION)latest[a.caseId]=a;return latest;}
function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function sourceLinks(ids, open=false){return `<details class="references" ${open?'open':''}><summary>Sources & further reading · ${ids.length}</summary>${ids.map(id=>sourceLink(sourceById[id])).join('')}<p class="foot-note">Original study summaries. Open the linked source for its full context; external pages need internet.</p></details>`;}
function sourceLink(s){if(!s)return '';return `<a class="reference-link" href="${esc(s.url)}" rel="noopener noreferrer">${icon('external')}<span><strong>${esc(s.title)}</strong><small>${esc(s.organization)} · Accessed ${esc(s.accessed)}</small></span></a>`;}
function header(eyebrow,title,description,extra=''){return `<div class="page-header"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${description}</p></div>${extra}</div>`;}
function button(action,label,value='',style='primary-button',ico='arrow'){return `<button class="${style}" data-action="${action}" data-value="${esc(value)}">${label}${ico?icon(ico):''}</button>`;}
function backButton(action,label,value=''){return `<button class="back-button" data-action="${action}" data-value="${esc(value)}">${icon('back')}${label}</button>`;}
function searchInput(label){return `<div class="search-wrap">${icon('search')}<input id="search" type="search" placeholder="${label}" aria-label="${label}" autocomplete="off" value="${esc(query)}"></div>`;}
function topicOptions(active=topicFilter){return `<option value="all">All regions</option>${topics.map(t=>`<option value="${t.id}" ${active===t.id?'selected':''}>${esc(t.title)}</option>`).join('')}`;}
const brainArt=`<svg viewBox="0 0 300 290" fill="none" aria-hidden="true"><g stroke="#abcba2" stroke-width=".65" opacity=".21"><circle cx="149" cy="130" r="104"/><circle cx="149" cy="130" r="89"/><path d="M24 130h251M149 9v250M64 43l170 172M62 216 236 42"/></g><g stroke="#c5d9ae" stroke-linecap="round" stroke-linejoin="round"><path d="M203 171c22-6 33-24 30-41 12-14 7-31-4-38 4-17-10-31-26-34-9-18-25-23-43-18-15-10-36-7-47 4-19-3-33 6-40 22-18 5-25 18-24 33-12 13-9 30 1 40-4 18 8 29 23 33 13 17 30 13 46 8l38-5" stroke-width="1.7"/><path d="M160 40c-10 9-13 22-8 31-13 9-18 17-14 30-15 10-10 25 0 28-7 14-3 29 14 33M114 44c6 13-4 24-13 27-13-4-27 3-28 15M74 66c3 12 11 19 23 18M50 99c14-6 27-2 31 11 15 1 24 11 19 23-11 7-15 17-8 30M49 139c13 0 23-5 23-15M74 172c-4-8-2-15 6-20M111 103c-9-8-10-21-3-29 11-6 21-5 30 1M120 93c5 7 3 19-5 24M102 133c12-4 24 2 25 12M113 176c-4-14 4-24 16-27M159 62c17-4 28 2 29 14 9 3 16 11 13 20 15 2 24 11 22 23M160 83c9 6 11 16 3 24M145 107c16 1 23 13 17 25M178 117c15-7 28 0 28 12M175 140c15-3 23 4 21 17M154 146c8 0 15 7 13 16M205 59c-10 7-10 15-5 20M230 92c-9-2-16 2-17 9M230 132c-9 1-18 8-16 18" stroke-width="1.25"/><path d="M178 166c19-4 37 3 39 17 4 18-11 28-28 23-11-2-21-8-25-18M164 174c-6 16 3 29 13 43l1 31-14 2-7-36c-10-12-22-23-18-39" stroke-width="1.6"/><path d="M178 176c14-4 24 0 30 7M173 182c13-3 24 1 31 7M176 189c8-1 17 2 23 7M171 214l2 30" stroke-width="1"/></g><g fill="#c9de83"><circle cx="107" cy="83" r="4"/><circle cx="154" cy="119" r="4"/><circle cx="160" cy="184" r="4"/><circle cx="194" cy="190" r="4"/></g><g stroke="#d7e8c1" stroke-width=".65" opacity=".7"><path d="M107 83 62 45H28M154 119l83-61h40M160 184l-81 39H31M194 190l34 35h49"/></g><g fill="#d1dfc2" font-family="Arial,sans-serif" font-size="6" letter-spacing="1"><text x="23" y="37">CORTEX</text><text x="241" y="49">DEEP</text><text x="23" y="237">BRAINSTEM</text><text x="221" y="240">CEREBELLUM</text></g></svg>`;
const pathwayArt=`<svg viewBox="0 0 100 235" fill="none" aria-hidden="true"><g stroke="currentColor" stroke-width="1.4" opacity=".55"><path d="M50 47c-7 9-20 4-20-5-13 0-15-15-8-22 0-13 18-16 25-8 10-13 28-6 28 6 12 7 11 23-2 27-2 8-12 8-18 4M50 11v32M37 20c-9 1-10 9-4 14m30-15c7 4 5 10-1 13M49 46l5 22-3 123M48 84 29 104 17 140m34-57 20 20 10 36M48 127l-20 46-7 47m32-92 18 47 10 47"/><path d="m23 122-9 2m5 9-10 2m65-14 12 3m-8 8 11 5M26 183l-11 6m7 12-11 6m63-20 13 5m-10 10 13 6"/></g><g fill="currentColor"><circle cx="50" cy="26" r="4"/><circle cx="52" cy="61" r="4"/><circle cx="51" cy="109" r="4"/><circle cx="29" cy="106" r="3"/><circle cx="21" cy="218" r="3"/></g></svg>`;

function renderNav(){const active=['topic','atlas','finder'].includes(view)?'learn':['session','results'].includes(view)?'cases':['flash','drills','drill'].includes(view)?'review':view;document.getElementById('navigation').innerHTML=[['home','home','Today'],['learn','book','Learn'],['cases','cases','Cases'],['review','cards','Review'],['library','library','Library']].map(([id,ico,label])=>`<button class="nav-item ${active===id?'active':''}" data-action="nav" data-value="${id}" ${active===id?'aria-current="page"':''}>${icon(ico)}<span class="nav-label">${label}</span>${id==='review'&&dueCards().length?`<span class="nav-dot">${dueCards().length}</span>`:''}</button>`).join('')+'<div class="nav-foot"><strong>A little practice.<br>A clearer picture.</strong><br><br>Built for focused study.<br>Available offline.</div>';}
function render({scroll=true,focus=false}={}){
  applySettings();renderNav();
  const views={home:renderHome,learn:renderLearn,topic:renderTopic,atlas:renderAtlas,cases:renderCases,session:renderSession,results:renderResults,review:renderReview,flash:renderFlash,library:renderLibrary,finder:renderFinder,drills:renderDrills,drill:renderDrill};
  main.innerHTML=(!storageOK?'<div class="storage-warning" role="status">Device storage is unavailable. Your progress may be lost when you close the app.</div>':'')+(views[view]||renderHome)();
  if(editionUpdated)main.insertAdjacentHTML('afterbegin','<div class="update-note" role="status"><div><strong>Your case bank has grown.</strong><p>Your progress and bookmarks are kept. Earlier sessions have ended because the original questions were revised. Start a new session to try the expanded bank.</p></div><button class="icon-button" data-action="dismiss-update" aria-label="Dismiss update notice">'+icon('close')+'</button></div>');
  if(scroll)window.scrollTo(0,0);
  if(focus) main.focus({preventScroll:true});
}
function navigate(next){view=next;detailId=null;query='';render({focus:true});}
function renderHome(){
 const readCount=Object.keys(state.read).length, studied=Object.keys(latestAttempts()).length;
 const correct=state.attempts.filter(a=>a.correct).length, accuracy=state.attempts.length?Math.round(correct/state.attempts.length*100)+'%':'—';
 const nextTopic=topics.find(t=>!state.read[t.id])||topics[0], daily=state.days[dateKey()]||{lessons:0,cases:0,cards:0};
 return `<div>${header('YOUR DAILY PRACTICE','A clearer way to localize.','Build clinical intuition, one finding at a time.',`<span class="date-label">${esc(new Date().toLocaleDateString('en',{weekday:'short',month:'short',day:'numeric'}))}</span>`)}
 ${state.session&&!state.session.complete?`<div class="session-resume"><div>Pick up where you left off<small>${Object.keys(state.session.answers).length} of ${state.session.ids.length} cases answered · ${state.session.mode==='exam'?'Test':'Tutor'} mode</small></div>${button('resume','Resume','','secondary-button')}</div>`:''}
 <section class="hero"><div class="hero-copy"><span class="eyebrow">${icon('spark')} THE DAILY FIVE</span><h2>Find the lesion.<br>Know the reason.</h2><p>Five clinical puzzles. Follow the findings from symptom to site.</p>${button('daily','Start a session','','accent-button')}</div><div class="hero-art"><span class="hero-sticker">ANATOMY → REASONING</span>${brainArt}<span class="hero-legend">CONCEPTUAL ANATOMY · NOT TO SCALE</span></div></section>
 <div class="stats-row"><div class="stat"><div class="stat-icon">${icon('flame')}</div><div><strong>${streak()} <small>day${streak()===1?'':'s'}</small></strong><span>Study streak</span></div></div><div class="stat"><div class="stat-icon">${icon('cases')}</div><div><strong>${studied}<small> / ${cases.length}</small></strong><span>Cases explored</span></div></div><div class="stat"><div class="stat-icon">${icon('target')}</div><div><strong>${accuracy}</strong><span>Answer accuracy</span></div></div></div>
 <div class="home-grid"><section><div class="section-head"><h2>${readCount?'Keep your momentum':'Begin with the essentials'}</h2>${button('nav','All lessons','learn','text-button')}</div><div class="card continue-card"><span class="small-tag">${esc(nextTopic.level)} · ${nextTopic.minutes} MIN READ</span><h3>${esc(nextTopic.title)}</h3><p>${esc(nextTopic.description)}</p><div class="progress-line"><span style="width:${readCount/topics.length*100}%"></span></div><div class="card-bottom"><span>${readCount} of ${topics.length} lessons completed</span>${button('topic','Open lesson',nextTopic.id,'text-button')}</div></div></section>
 <section><div class="section-head"><h2>A small plan for today</h2><span class="muted" style="font-size:.62rem">YOUR PACE, YOUR PROGRESS</span></div><div class="card plan-card">${planRow(daily.lessons>0,'01','Learn one region',`${daily.lessons} lesson${daily.lessons===1?'':'s'} completed today`,'topic',nextTopic.id)}${planRow(daily.cases>=5,'02','Reason through five cases',`${daily.cases} case${daily.cases===1?'':'s'} answered today`,'daily')}${planRow(daily.cards>=5,'03','Make it stick',`${daily.cards} recall card${daily.cards===1?'':'s'} reviewed today`,'review-start')}</div></section></div>
 <div class="tool-row"><button class="card tool-card" data-action="nav" data-value="finder"><span class="tool-icon">${icon('compass')}</span><span><strong>Pattern finder</strong><small>Tick the findings. See which levels explain them and which argue against.</small></span>${icon('chevron','chevron')}</button><button class="card tool-card" data-action="nav" data-value="atlas"><span class="tool-icon">${icon('eye')}</span><span><strong>Visual atlas · ${atlas.length} diagrams</strong><small>Pathways, cross-sections, decision trees and comparison charts.</small></span>${icon('chevron','chevron')}</button><button class="card tool-card" data-action="nav" data-value="drills"><span class="tool-icon">${icon('flame')}</span><span><strong>Rapid drills · ${drills.length} decks</strong><small>Quick-fire questions on roots, fields, aphasias, eye muscles and nerves.</small></span>${icon('chevron','chevron')}</button></div>
 <div class="source-banner">${icon('shield')}<div><strong>Study the pattern. Follow the evidence.</strong><p>Original teaching content linked to Merck Manual Professional, NCBI Bookshelf, and academic resources. Built for education; not independently clinician-reviewed.</p></div></div></div>`;
}
function planRow(done,n,title,subtitle,action,value=''){return `<button class="plan-row" data-action="${action}" data-value="${esc(value)}"><span class="step-circle ${done?'done':''}">${done?icon('check'):n}</span><span><strong>${title}</strong><small>${subtitle}</small></span>${icon('chevron','chevron')}</button>`;}
function renderLearn(){
 const filtered=topics.filter(t=>(learnFilter==='all'||(learnFilter==='unread'?!state.read[t.id]:t.level===learnFilter))&&[t.title,t.description,t.summary,...t.sections.flatMap(s=>[s.heading,s.text,...(s.bullets||[])]),...t.pearls,t.pitfall].join(' ').toLowerCase().includes(query.toLowerCase()));
 return `<div>${header('THE LEARNING ATLAS','Build your mental map.','From cortex to muscle. Learn the clues that connect a finding to its anatomical home.')}
 <div class="learning-progress">${icon('book')}<div><strong>${Object.keys(state.read).length} of ${topics.length} lessons completed</strong><div class="progress-line"><span style="width:${Object.keys(state.read).length/topics.length*100}%"></span></div></div><small>${cards.length} recall cards<br>${cases.length} clinical cases</small></div>
 <div class="visual-entry"><div><span class="eyebrow">LEARN BY SEEING</span><strong>Your visual anatomy atlas</strong><p>${atlas.length} labeled diagrams with zoom and source-linked explanations.</p></div>${button('nav','Explore images','atlas','secondary-button','eye')}</div><div class="visual-entry"><div><span class="eyebrow">REASON IT THROUGH</span><strong>Pattern finder</strong><p>Choose findings and watch the candidate levels rise and fall.</p></div>${button('nav','Open the finder','finder','secondary-button','compass')}</div>
 <div class="toolbar">${searchInput('Search lessons, anatomy, or a finding')}</div><div class="filter-chips">${['all','Foundation','Intermediate','Advanced','unread'].map(x=>`<button class="chip ${learnFilter===x?'active':''}" data-action="learn-filter" data-value="${x}" aria-pressed="${learnFilter===x}">${x==='all'?'All lessons':x==='unread'?'Not completed':x}</button>`).join('')}</div>
 <div id="search-results"><div class="topic-grid">${filtered.map(t=>topicCard(t)).join('')}</div>${filtered.length?'':empty('No lessons found.','Try a region such as “cord” or clear your filters.','clear-filters','Clear filters')}</div>
 <div class="pathway-map">${pathwayArt}<div><h3>Think along the neuraxis.</h3><div class="pathway-stops">${['cortex','subcortex','brainstem','cord','roots','plexus','nerves','nmj','muscle'].filter(id=>topicById[id]).map(id=>`<button data-action="topic" data-value="${id}">${esc(topicById[id].title)}</button>`).join('')}</div><p>A conceptual route through localization. Explore each region to see its characteristic pattern.</p></div></div></div>`;
}
function topicCard(t){return `<button class="card topic-card" data-action="topic" data-value="${t.id}"><span class="topic-card-top"><span class="topic-icon">${icon(t.icon)}</span><span class="topic-number">${String(topics.indexOf(t)+1).padStart(2,'0')}</span></span><span class="eyebrow">${esc(t.kicker)}</span><h3>${esc(t.title)}</h3><p>${esc(t.description)}</p><span class="topic-meta"><span>${t.minutes} min · ${esc(t.level)}</span>${state.read[t.id]?`<span class="sr-only">Completed</span>${icon('check')}`:icon('arrow')}</span></button>`;}
function renderTopic(){const t=topicById[detailId];if(!t)return renderLearn();return `<article class="article">${backButton('nav','Learning atlas','learn')}<header class="article-header"><span class="eyebrow">LESSON ${String(topics.indexOf(t)+1).padStart(2,'0')} · ${esc(t.kicker)}</span><h1>${esc(t.title)}</h1><p>${esc(t.description)}</p><div class="article-meta"><span>${t.minutes} min read</span><span>${esc(t.level)}</span><span>${t.sourceIds.length} sources</span></div></header><p class="article-lead">${esc(t.summary)}</p>${diagramFor(t.id,true)}${t.sections.map((s,i)=>`<section class="article-section"><span class="eyebrow muted">0${i+1}</span><h2>${esc(s.heading)}</h2><p>${esc(s.text)}</p>${s.bullets?.length?`<ul>${s.bullets.map(b=>`<li>${esc(b)}</li>`).join('')}</ul>`:''}</section>`).join('')}<aside class="pearl-panel"><span class="eyebrow">ANCHOR POINTS</span><ul>${t.pearls.map(p=>`<li>${esc(p)}</li>`).join('')}</ul></aside><aside class="pitfall"><strong>A common trap</strong>${esc(t.pitfall)}</aside>${sourceLinks(t.sourceIds)}<div class="button-row">${button('complete-topic',state.read[t.id]?'Lesson completed':'Mark as learned',t.id,state.read[t.id]?'secondary-button':'primary-button','check')}${cases.some(c=>c.topicId===t.id)?button('topic-cases','Practice this region',t.id,'secondary-button'):''}${t.drill&&drillById[t.drill]?button('drill-start','Rapid drill: '+esc(drillById[t.drill].title),t.drill,'secondary-button','flame'):''}</div><p class="foot-note">Learning summaries describe typical patterns. Real presentations vary and need clinical assessment.</p></article>`;}
function renderCases(){let filtered=filteredCases();return `<div>${header('CLINICAL REASONING','Every finding tells a story.','Compare close alternatives. Localize a lesion, choose a discriminating sign, or predict the next finding.')}<section class="practice-banner"><div><span class="eyebrow" style="color:#c1d99b;font-size:.56rem">${cases.length} CLINICAL PUZZLES</span><h2>Weigh the close alternatives.</h2><p>Tutor mode explains each answer. Tests withhold feedback until the end. Mixed sessions sample different regions and question types.</p></div><div class="button-row">${button('daily','5-case tutor','','accent-button')}${button('exam','10-case test','','secondary-button')}${button('challenge','Advanced challenge','','secondary-button','target')}${button('revisit-misses','Revisit my misses','','secondary-button','reset')}</div></section>
 ${state.session&&!state.session.complete?`<div class="session-resume" style="margin-top:18px"><div>A session is waiting<small>${Object.keys(state.session.answers).length}/${state.session.ids.length} answered</small></div>${button('resume','Resume','','text-button')}</div>`:''}
 <div class="toolbar">${searchInput('Search cases or clinical findings')}<select id="topic-filter" aria-label="Filter cases by region">${topicOptions()}</select><select id="difficulty-filter" aria-label="Filter cases by difficulty">${['all','Foundation','Intermediate','Advanced'].map(x=>`<option value="${x}" ${difficultyFilter===x?'selected':''}>${x==='all'?'All levels':x}</option>`).join('')}</select><button class="chip ${onlySaved?'active':''}" data-action="saved-filter" aria-pressed="${onlySaved}">Saved cases${onlySaved?' ✓':''}</button></div><div class="filter-chips" aria-label="Question skill">${[['all','All question types'],['Localize','Find the location'],['Discriminate','Separate close alternatives'],['Predict','Predict a finding']].map(([id,label])=>`<button class="chip ${taskFilter===id?'active':''}" data-action="task-filter" data-value="${id}" aria-pressed="${taskFilter===id}">${label}</button>`).join('')}</div><div id="search-results"><p class="case-count">${filtered.length} case${filtered.length===1?'':'s'} in this collection</p><div class="case-list">${filtered.map(c=>caseRow(c)).join('')}</div>${filtered.length?'':empty('No cases in this view.','Try a different region, or save cases using the bookmark inside a case.','clear-filters','Show all cases')}</div></div>`;}
function caseMatchesTopic(c,id){return id==='all'||c.topicId===id||(id==='motor'&&['approach','subcortex','roots','nerves','nmj','muscle'].includes(c.topicId)&&/weak|reflex|plantar|power|ptosis/i.test(c.findings.join(' ')));}
function filteredCases(){return cases.filter(c=>caseMatchesTopic(c,topicFilter)&&(difficultyFilter==='all'||c.difficulty===difficultyFilter)&&(taskFilter==='all'||(c.taskType||'Localize')===taskFilter)&&(!onlySaved||state.bookmarks[c.id])&&`${c.title} ${c.stem} ${c.question} ${c.findings.join(' ')} ${topicById[c.topicId]?.title||''}`.toLowerCase().includes(query.toLowerCase()));}
function caseRow(c){const a=latestAttempts()[c.id];return `<button class="case-row" data-action="case" data-value="${c.id}"><span class="case-index">${String(cases.indexOf(c)+1).padStart(3,'0')}</span><div><span class="case-tags"><span class="pill ${c.difficulty}">${esc(c.difficulty)}</span><span class="pill">${esc(c.taskType||'Localize')}</span><span class="case-status">${state.bookmarks[c.id]?icon('bookmark'):''}${a?(a.bankRevision===BANK_REVISION?`${icon(a.correct?'check':'reset')}${a.correct?'Last answer correct':'Revisit this case'}`:'Revised · try again'):'Not attempted'}</span></span><h3>${esc(c.title)}</h3><p>${esc(c.stem)}</p></div>${icon('chevron','chevron')}</button>`;}
function startSession(ids,mode='tutor',replace=false){
 if(!ids.length){toast('No cases match this collection. Try all regions.');return;}
 if(state.session&&!state.session.complete&&!replace){pendingSession={ids,mode};openSheet('A session is in progress',`<p class="about-copy">You have answered ${Object.keys(state.session.answers).length} of ${state.session.ids.length} cases. Resume it, or replace it with a new session. Completed results stay in history. Replacing an unfinished test clears its unscored answers.</p><div class="button-row">${button('resume','Resume session','','primary-button')}${button('replace-session','Start new session','','secondary-button')}</div>`);return;}
 state.session={uid:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,9),bankRevision:BANK_REVISION,mode,ids,index:0,answers:{},optionOrders:practice.makeOptionOrders(ids,caseById),complete:false};selected=null;save();view='session';render({focus:true});
}
function recordAnswer(c,answerId,uid){const key=uid+':'+c.id;if(state.attempts.some(a=>a.key===key))return;state.attempts.push({key,caseId:c.id,answerId,correct:c.answerId===answerId,time:Date.now(),bankRevision:BANK_REVISION});state.attempts=state.attempts.slice(-3000);activity('cases');}
function renderSession(){
 const s=state.session;if(!s)return empty('Choose a clinical puzzle.','Start a tutor session from the cases library.','nav','Browse cases','cases');
 if(s.complete)return renderResults();
 const c=caseById[s.ids[s.index]], answer=s.answers[c.id], revealed=!!answer&&s.mode==='tutor';
 const ordered=s.optionOrders[c.id].map(id=>c.options.find(o=>o.id===id));
 return `<div class="session"><div class="session-toolbar">${backButton('nav','Save & leave','cases')}<span class="session-count">${s.mode==='exam'?'TEST':'TUTOR'} · CASE ${s.index+1} / ${s.ids.length}</span></div><div class="progress-line session-progress"><span style="width:${s.index/s.ids.length*100}%"></span></div><div class="case-header"><span class="eyebrow">THE CLINICAL PICTURE</span><button class="icon-button bookmark-button ${state.bookmarks[c.id]?'saved':''}" data-action="bookmark" data-value="${c.id}" aria-label="${state.bookmarks[c.id]?'Unsave':'Save'} this case" aria-pressed="${!!state.bookmarks[c.id]}">${icon('bookmark')}</button></div><h1>Clinical case ${String(cases.indexOf(c)+1).padStart(3,'0')}</h1><div class="vignette"><p>${esc(c.stem)}</p><ul class="finding-list">${c.findings.map(f=>`<li>${esc(f)}</li>`).join('')}</ul></div><h2 class="question">${esc(c.question)}</h2><div class="answer-list" role="group" aria-label="Answer choices">${ordered.map((o,displayIndex)=>`<button class="answer-option ${(!answer&&selected===o.id)?'selected':''} ${revealed?(o.id===c.answerId?'correct':o.id===answer?'incorrect':''):''}" data-action="select-answer" data-value="${o.id}" ${answer?'disabled':''} aria-pressed="${(answer||selected)===o.id}"><span class="answer-letter">${'ABCD'[displayIndex]}</span><span>${esc(o.text)}${revealed?`<span class="answer-state ${o.id===answer&&o.id!==c.answerId?'wrong':''}">${o.id===c.answerId?'Best answer':o.id===answer?'Your answer':''}</span><small>${esc(o.explanation)}</small>`:''}</span>${revealed&&(o.id===c.answerId||o.id===answer)?`<span class="answer-symbol">${icon(o.id===c.answerId?'check':'close')}</span>`:''}</button>`).join('')}</div>
 ${revealed?feedback(c,answer):''}<div class="session-footer"><p>${revealed?'A pattern is a clue, not proof.':s.mode==='exam'?'Explanations appear after your final case.':'Weigh the positive and negative findings.'}</p>${answer?button('next-case',s.index===s.ids.length-1?'Finish session':'Next case'): `<button class="primary-button" data-action="submit-answer" ${!selected?'disabled':''}>${s.mode==='exam'?'Lock in & continue':'Check my reasoning'}${icon('arrow')}</button>`}</div></div>`;
}
function diagramImage(d){return '<img src="assets/atlas/'+esc(d.id)+'.svg" alt="'+esc(d.alt)+'" width="720" height="'+(d.h||560)+'" loading="lazy">';}
function diagramsFor(topicId){return atlas.filter(d=>d.topics.includes(topicId));}
function diagramFor(topicId,more=false){const list=diagramsFor(topicId),d=list[0];if(!d)return '';const rest=more?list.slice(1):[];return '<figure class="anatomy-figure"><div class="diagram-heading"><span class="eyebrow">VISUAL ANATOMY</span><span class="muted">Schematic</span></div><button class="diagram-image" data-action="diagram" data-value="'+esc(d.id)+'" aria-label="Enlarge diagram: '+esc(d.title)+'">'+diagramImage(d)+'</button><figcaption><strong>'+esc(d.title)+'</strong><p>'+esc(d.caption)+'</p><button class="text-button" data-action="diagram" data-value="'+esc(d.id)+'">Enlarge & explore '+icon('eye')+'</button></figcaption><details class="diagram-notes"><summary>Read the diagram</summary><p>'+esc(d.explanation)+'</p>'+sourceLinks(d.sourceIds)+'</details>'+(rest.length?'<div class="thumb-strip"><span class="eyebrow">MORE VISUALS FOR THIS REGION · '+rest.length+'</span><div class="thumb-row">'+rest.map(x=>'<button class="thumb" data-action="diagram" data-value="'+esc(x.id)+'">'+diagramImage(x)+'<span>'+esc(x.title)+'</span></button>').join('')+'</div></div>':'')+'</figure>';}
function atlasGroups(){return [...new Set(atlas.map(d=>d.group||'Other'))];}
function filteredAtlas(){return atlas.filter(d=>(atlasGroup==='all'||(d.group||'Other')===atlasGroup)&&[d.title,d.caption,d.alt,d.explanation].join(' ').toLowerCase().includes(query.toLowerCase()));}
function renderAtlas(){const list=filteredAtlas();return '<div>'+backButton('nav','Learning atlas','learn')+header('THE VISUAL ATLAS','See the connections.',atlas.length+' original anatomy diagrams: pathways, cross-sections, decision trees and comparison charts. Open any image to zoom, step through the atlas and explore its references.')+'<p class="foot-note">Simplified educational schematics, not clinical scans or exact anatomical measurements. In cases, these illustrations appear only after you answer.</p><div class="toolbar">'+searchInput('Search diagrams, e.g. “chiasm” or “plexus”')+'</div><div class="filter-chips" aria-label="Diagram region">'+['all',...atlasGroups()].map(g=>'<button class="chip '+(atlasGroup===g?'active':'')+'" data-action="atlas-group" data-value="'+esc(g)+'" aria-pressed="'+(atlasGroup===g)+'">'+(g==='all'?'All diagrams · '+atlas.length:esc(g)+' · '+atlas.filter(d=>(d.group||'Other')===g).length)+'</button>').join('')+'</div><div id="search-results">'+(list.length?'':empty('No diagrams found.','Try another word or clear the filter.','clear-filters','Show all diagrams'))+'<div class="atlas-grid">'+list.map(d=>'<button class="card atlas-card" data-action="diagram" data-value="'+esc(d.id)+'">'+diagramImage(d)+'<span><span class="eyebrow">'+esc(d.group||'')+'</span><strong>'+esc(d.title)+'</strong><small>'+esc(d.caption)+'</small></span></button>').join('')+'</div></div></div>';}
function showDiagram(id){const d=diagramById[id];if(!d)return;currentDiagram=id;diagramZoom=1;const i=atlas.indexOf(d),prev=atlas[(i-1+atlas.length)%atlas.length],next=atlas[(i+1)%atlas.length],lesson=topicById[d.topics[0]];openSheet(esc(d.title),'<div class="diagram-controls">'+[1,2,3].map(z=>'<button class="secondary-button zoom-button '+(z===1?'active':'')+'" data-action="diagram-scale" data-value="'+z+'" aria-pressed="'+(z===1)+'">'+(z===1?'Fit':'Zoom '+z+'×')+'</button>').join('')+'<span id="diagram-zoom-status" class="muted" role="status">Fit to screen · '+(i+1)+' of '+atlas.length+'</span></div><div class="diagram-viewport" tabindex="0" aria-label="Diagram; when zoomed, scroll or drag to explore">'+diagramImage(d)+'</div><div class="diagram-nav"><button class="secondary-button" data-action="diagram" data-value="'+esc(prev.id)+'" aria-label="Previous diagram: '+esc(prev.title)+'">'+icon('prev')+'<span>'+esc(prev.title)+'</span></button><button class="secondary-button" data-action="diagram" data-value="'+esc(next.id)+'" aria-label="Next diagram: '+esc(next.title)+'"><span>'+esc(next.title)+'</span>'+icon('chevron')+'</button></div><p class="diagram-description">'+esc(d.explanation)+'</p>'+(lesson&&view!=='topic'?'<div class="button-row" style="margin-bottom:14px">'+button('topic-from-diagram','Open lesson: '+esc(lesson.title),lesson.id,'text-button','book')+'</div>':'')+'<p class="foot-note">Original NeuroLocalize illustration · reviewed against the linked teaching references on 8 October 2026 · simplified and not to scale.</p>'+sourceLinks(d.sourceIds));sheet.classList.add('diagram-sheet');}
function contrast(c){return c.discriminator||c.alternative?`<div class="contrast-panel">${c.discriminator?`<div><span class="eyebrow">THE DECIDING DETAIL</span><p>${esc(c.discriminator)}</p></div>`:''}${c.alternative?`<div><span class="eyebrow">THE CLOSEST ALTERNATIVE</span><p>${esc(c.alternative)}</p></div>`:''}</div>`:'';}
function feedback(c,answer){return `<section class="feedback" id="feedback" aria-label="Answer explanation"><div class="feedback-label ${answer===c.answerId?'':'wrong'}">${answer===c.answerId?'SOUND REASONING':'A USEFUL LEARNING MOMENT'}</div><h2>Follow the anatomy.</h2><p class="muted" style="font-size:.76rem">${esc(c.title)}</p><ol>${c.reasoning.map(r=>`<li>${esc(r)}</li>`).join('')}</ol>${contrast(c)}${diagramFor(c.topicId)}<div class="pearl-panel"><span class="eyebrow">TAKE THIS WITH YOU</span><p>${esc(c.pearl)}</p></div>${sourceLinks(c.sourceIds)}</section>`;}
function submitAnswer(){const s=state.session;if(!s||s.complete||!selected)return;const c=caseById[s.ids[s.index]];if(s.answers[c.id])return;s.answers[c.id]=selected;if(s.mode==='tutor')recordAnswer(c,selected,s.uid);selected=null;save();if(s.mode==='exam'){nextCase();return;}render({scroll:false});requestAnimationFrame(()=>document.getElementById('feedback')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'}));}
function nextCase(){const s=state.session;if(!s||!s.answers[s.ids[s.index]])return;if(s.index<s.ids.length-1){s.index++;view='session';}else{s.complete=true;if(s.mode==='exam')for(const id of s.ids)recordAnswer(caseById[id],s.answers[id],s.uid);view='results';}selected=null;save();render({focus:true});}
function renderResults(){const s=state.session;if(!s||!s.complete)return renderCases();const correct=s.ids.filter(id=>s.answers[id]===caseById[id].answerId).length;return `<div class="session">${backButton('nav','Case library','cases')}<section class="result-hero"><span class="eyebrow">SESSION COMPLETE</span><div class="result-ring"><strong>${correct}<span style="font-size:1rem"> / ${s.ids.length}</span></strong><small>CORRECT</small></div><h1>${correct===s.ids.length?'A well-connected map.':'Every case adds a connection.'}</h1><p>${correct===s.ids.length?'Keep your reasoning sharp with a different region.':'Revisit the reasoning below, then put the key patterns into practice.'}</p><div class="button-row">${correct<s.ids.length?button('retry-missed','Revisit missed cases','','primary-button'):button('daily','Practice five more','','primary-button')}${button('nav','Recall cards','review','secondary-button','cards')}</div></section><div class="section-head"><h2>Your reasoning review</h2><span class="muted" style="font-size:.67rem">Tap a case to unpack it</span></div>${s.ids.map(id=>resultDetails(caseById[id],s.answers[id])).join('')}<p class="foot-note">This score reflects this practice session. It is not a validated assessment of clinical competence.</p></div>`;}
function resultDetails(c,answer){const chosen=c.options.find(o=>o.id===answer),best=c.options.find(o=>o.id===c.answerId);return `<details class="result-details"><summary>${answer===c.answerId?'✓':'○'} ${esc(c.title)}<small>${answer===c.answerId?'Correct':'Review recommended'} · ${esc(c.difficulty)}</small></summary><div class="result-explain"><p>${esc(c.stem)} ${esc(c.findings.join(' '))}</p><p><strong>Your answer:</strong> ${esc(chosen?.text)}</p><span class="answer-state">Best answer: ${esc(best.text)}</span><ol>${c.reasoning.map(r=>`<li>${esc(r)}</li>`).join('')}</ol>${contrast(c)}${diagramFor(c.topicId)}<h3>Why the alternatives fit less well</h3>${c.options.filter(o=>o.id!==c.answerId).map(o=>`<p><strong>${esc(o.text)}:</strong> ${esc(o.explanation)}</p>`).join('')}<div class="pearl-panel"><p>${esc(c.pearl)}</p></div>${sourceLinks(c.sourceIds)}${button('bookmark',state.bookmarks[c.id]?'Remove bookmark':'Save this case',c.id,'text-button','bookmark')}</div></details>`;}
function renderReview(){const region=cards.filter(c=>reviewFilter==='all'||c.topicId===reviewFilter),due=dueCards().filter(c=>reviewFilter==='all'||c.topicId===reviewFilter).length,reviewed=region.filter(c=>state.reviews[c.id]).length;return `<div class="review-hub">${header('RETRIEVAL PRACTICE','Make the connections last.','Recall first. Reveal second. Return to difficult patterns more often.')}<div class="review-intro"><div><span class="eyebrow" style="font-size:.58rem">${reviewFilter==='all'?'YOUR REVIEW QUEUE':esc(topicById[reviewFilter].title)}</span><h2>${due?`${due} cards ready for you.`:'All caught up for now.'}</h2><p>${due?'A mix of new cards and scheduled reviews. Start with up to ten at a time.':'Your next reviews will appear when due. You can still revisit this collection for extra practice.'}</p>${button('review-start',due?'Start a review':'Practice this collection','','primary-button')}</div><div class="review-stack"><span>${due}<small>READY</small></span></div></div><div class="toolbar"><select id="review-topic-filter" aria-label="Filter recall cards by region">${topicOptions(reviewFilter)}</select>${button('review-all','Practice this collection','','secondary-button','cards')}</div><p class="foot-note">${reviewed} of ${region.length} cards seen in this collection. “Again” returns in 1 minute; “Good” starts at 1 day; “Easy” starts at 7 days. Intervals grow with repeated recall. Optional practice also updates the schedule.</p><div class="section-head"><h2>Rapid drills</h2>${button('nav','All decks','drills','text-button')}</div>${drillGrid(3)}<div class="section-head"><h2>Your study rhythm</h2><span class="muted" style="font-size:.64rem">LAST 12 WEEKS</span></div>${heatmap()}${skillRows()}<div class="section-head"><h2>Your regional confidence</h2><span class="muted" style="font-size:.64rem">LATEST CASE ANSWERS</span></div><div class="card strength-list">${strengthRows()}</div><p class="foot-note">Bars show your latest answers to this edition’s cases. Earlier results stay in your overall history; revised cases need a new attempt. They are study signals, not measures of clinical competence.</p></div>`;}
function strengthRows(){const latest=latestAttempts(true);return topics.map(t=>{const regionCases=cases.filter(c=>c.topicId===t.id);if(!regionCases.length)return '';const seen=regionCases.filter(c=>latest[c.id]),correct=seen.filter(c=>latest[c.id].correct).length;return `<div class="strength-row"><div class="strength-top"><strong>${esc(t.title)}</strong><span>${seen.length?`${correct}/${seen.length} correct · ${regionCases.length-seen.length} unseen`:'Not explored yet'}</span></div><div class="progress-line"><span style="width:${seen.length?correct/seen.length*100:0}%"></span></div></div>`;}).join('');}
function heatmap(){const today=new Date();today.setHours(0,0,0,0);const start=new Date(today);start.setDate(start.getDate()-start.getDay()-77);const cells=[];let total=0,active=0;for(let d=new Date(start);d<=today;d.setDate(d.getDate()+1)){const v=state.days[dateKey(d.getTime())],n=v?v.lessons+v.cases+v.cards:0;total+=n;if(n)active++;const lvl=n===0?0:n<4?1:n<10?2:n<20?3:4;cells.push('<span class="heat l'+lvl+'" title="'+esc(d.toLocaleDateString('en',{month:'short',day:'numeric'}))+': '+n+' activit'+(n===1?'y':'ies')+'"></span>');}return '<div class="card heat-card"><div class="heat-grid" role="img" aria-label="Study activity over the last 12 weeks: '+active+' active days, '+total+' activities">'+cells.join('')+'</div><div class="heat-foot"><span>'+active+' active day'+(active===1?'':'s')+' · '+total+' lessons, cases and cards</span><span class="heat-key">Less <i class="heat l0"></i><i class="heat l1"></i><i class="heat l2"></i><i class="heat l3"></i><i class="heat l4"></i> More</span></div></div>';}
function skillRows(){const latest=Object.values(latestAttempts(true));if(!latest.length)return '';return '<div class="skill-grid">'+[['Localize','Find the location'],['Discriminate','Separate alternatives'],['Predict','Predict a finding']].map(([k,label])=>{const xs=latest.filter(a=>(caseById[a.caseId].taskType||'Localize')===k),c=xs.filter(a=>a.correct).length,pct=xs.length?Math.round(c/xs.length*100):0;return '<div class="card skill-card"><span class="eyebrow">'+label.toUpperCase()+'</span><div class="skill-ring" style="--p:'+pct+'"><strong>'+(xs.length?pct+'%':'—')+'</strong></div><small>'+(xs.length?c+' of '+xs.length+' correct':'Not tried yet')+'</small></div>';}).join('')+'</div>';}
function startFlash(all=false){const pool=(all?cards:dueCards()).filter(c=>reviewFilter==='all'||c.topicId===reviewFilter);if(!pool.length){if(!all){startFlash(true);return;}toast('No cards in this collection.');return;}flash={ids:shuffle(pool).slice(0,10).map(c=>c.id),index:0,revealed:false,done:false};view='flash';render({focus:true});}
function reviewInterval(card,grade){const old=state.reviews[card.id]?.interval||0;return grade==='again'?1/1440:grade==='good'?(old>=1?Math.min(180,Math.round(old*2.2)):1):Math.min(365,Math.max(7,Math.round(old*3)));}
function intervalLabel(days){return days<1?'In 1 minute':days===1?'In 1 day':`In ${days} days`;}
function renderFlash(){if(!flash)return renderReview();if(flash.done)return `<div class="review-hub">${empty('A little more connected.',`You reviewed ${flash.ids.length} cards. Your next reviews are scheduled on this device.`,'nav','Back to review','review','leaf')}${button('review-start','Review another set','','secondary-button')}</div>`;const c=cardById[flash.ids[flash.index]];return `<div class="review-hub"><div class="session-toolbar">${backButton('nav','Review collection','review')}<span class="session-count">CARD ${flash.index+1} / ${flash.ids.length}</span></div><div class="progress-line"><span style="width:${flash.index/flash.ids.length*100}%"></span></div><div class="flashcard"><span class="eyebrow">${esc(topicById[c.topicId]?.title||'RECALL')}</span><h2>${esc(c.front)}</h2>${flash.revealed?`<div class="flashcard-back" id="flash-answer">${esc(c.back)}</div>`:'<p class="muted" style="font-size:.75rem;margin:15px 0 0">Form your answer before you reveal it.</p>'}</div>${flash.revealed?`<p class="muted" style="font-size:.73rem;text-align:center">How easily did you recall the answer?</p><div class="review-ratings">${['again','good','easy'].map(g=>`<button class="rating-button ${g}" data-action="rate-card" data-value="${g}">${g[0].toUpperCase()+g.slice(1)}<small>${intervalLabel(reviewInterval(c,g))}</small></button>`).join('')}</div>${sourceLinks(c.sourceIds)}`:`${button('reveal-card','Reveal answer','','primary-button','eye')}<p class="foot-note">Try saying the location and the reason out loud.</p>`}</div>`;}
function rateCard(grade){if(!flash||flash.done||!flash.revealed||!['again','good','easy'].includes(grade))return;const c=cardById[flash.ids[flash.index]],interval=reviewInterval(c,grade);state.reviews[c.id]={due:Date.now()+interval*DAY,interval,count:(state.reviews[c.id]?.count||0)+1};activity('cards');flash.index++;flash.done=flash.index>=flash.ids.length;flash.revealed=false;save();render({focus:true});}
function uniqueSources(){const urls=new Set();return sources.filter(s=>{const u=new URL(s.url);const canonical=u.origin+u.pathname.replace('/sites/books/','/books/').replace(/\/$/,'');if(urls.has(canonical))return false;urls.add(canonical);return true;});}
function renderLibrary(){const all=uniqueSources(),filtered=all.filter(s=>`${s.title} ${s.organization} ${s.note}`.toLowerCase().includes(query.toLowerCase()));return `<div>${header('THE REFERENCE SHELF','Good reasoning has roots.','Explore the resources behind your lessons, clinical puzzles, and recall cards.')}<div class="visual-entry"><div><strong>Visual anatomy atlas</strong><p>Explore the illustrations and their references.</p></div>${button('nav','Explore images','atlas','secondary-button','eye')}</div><div class="about-note"><strong>Transparent by design.</strong><p>Teaching content is written in original language and linked to established medical references. Reference notes show the access date and review scope for each source. This is not an endorsement by those organizations or an independent clinical review of this app.</p><p>All study content works offline. Full external references require internet and may have access restrictions.</p></div><div class="toolbar">${searchInput('Search sources, titles, or organizations')}</div><div id="search-results"><p class="case-count">${filtered.length} resources · cited within the teaching content</p><div class="source-grid">${filtered.map(s=>`<a class="card source-card" href="${esc(s.url)}" rel="noopener noreferrer"><span class="eyebrow">${esc(s.organization)}</span><h3>${esc(s.title)}</h3><p>${esc(s.note)}</p><span class="source-card-foot"><span>Accessed ${esc(s.accessed)}</span>${icon('external')}</span></a>`).join('')}</div>${filtered.length?'':empty('No matching sources.','Try searching an organization or anatomical region.','clear-filters','Clear search')}</div><p class="foot-note">NeuroLocalize ${APP_VERSION} · Educational use only. Synthetic cases illustrate typical patterns. Do not use this app to diagnose, triage, or manage a patient. New neurological symptoms require appropriate medical evaluation.</p></div>`;}
function drillGrid(limit=drills.length){return '<div class="drill-grid">'+drills.slice(0,limit).map(d=>{const r=state.drills[d.id];return '<button class="card drill-card" data-action="drill-start" data-value="'+d.id+'"><span class="eyebrow">'+d.items.length+' QUESTIONS</span><strong>'+esc(d.title)+'</strong><small>'+esc(d.description)+'</small><span class="drill-best">'+(r?'Best '+r.best+'% · '+r.plays+' run'+(r.plays===1?'':'s'):'Not tried yet')+'</span></button>';}).join('')+'</div>';}
function renderDrills(){return '<div class="review-hub">'+backButton('nav','Review','review')+header('RAPID DRILLS','Fast recall, instant feedback.','Short runs of up to ten questions built from the atlas tables. Answers are checked as you go; your best score is kept on this device.')+drillGrid()+'<p class="foot-note">Drills test recall of classic patterns. Real presentations vary.</p></div>';}
function startDrill(id){const d=drillById[id];if(!d)return;const answers=[...new Set(d.items.map(i=>i[1]))];const qs=practice.shuffle(d.items).slice(0,10).map(([q,a])=>({q,a,options:practice.shuffle([a,...practice.shuffle(answers.filter(x=>x!==a)).slice(0,3)])}));drill={deck:id,qs,index:0,picks:[],done:false};view='drill';render({focus:true});}
function renderDrill(){if(!drill)return renderDrills();const d=drillById[drill.deck];if(drill.done){const correct=drill.qs.filter((q,i)=>drill.picks[i]===q.a).length,pct=Math.round(correct/drill.qs.length*100),r=state.drills[d.id];return '<div class="session">'+backButton('nav','All drills','drills')+'<section class="result-hero"><span class="eyebrow">'+esc(d.title).toUpperCase()+'</span><div class="result-ring"><strong>'+correct+'<span style="font-size:1rem"> / '+drill.qs.length+'</span></strong><small>CORRECT</small></div><h1>'+(pct===100?'Flawless.':pct>=70?'Solid recall.':'Worth another run.')+'</h1><p>'+(r&&r.best===pct&&r.plays>1?'A new best for this deck.':'Best so far: '+(r?r.best:pct)+'%')+'</p><div class="button-row">'+button('drill-start','Run it again',d.id,'primary-button','reset')+button('diagram','See the diagram',d.diagram,'secondary-button','eye')+'</div></section><div class="section-head"><h2>Your answers</h2></div><div class="card drill-review">'+drill.qs.map((q,i)=>'<div class="drill-row '+(drill.picks[i]===q.a?'ok':'miss')+'"><span>'+icon(drill.picks[i]===q.a?'check':'close')+'</span><div><strong>'+esc(q.q)+'</strong><small>'+(drill.picks[i]===q.a?esc(q.a):'Answer: '+esc(q.a)+' · you chose '+esc(drill.picks[i]))+'</small></div></div>').join('')+'</div></div>';}
 const q=drill.qs[drill.index],pick=drill.picks[drill.index];return '<div class="session"><div class="session-toolbar">'+backButton('nav','Leave drill','drills')+'<span class="session-count">'+esc(d.title).toUpperCase()+' · '+(drill.index+1)+' / '+drill.qs.length+'</span></div><div class="progress-line session-progress"><span style="width:'+(drill.index/drill.qs.length*100)+'%"></span></div><span class="eyebrow" style="margin-top:26px">'+esc(d.prompt)+'</span><h1 class="drill-q">'+esc(q.q)+'</h1><div class="answer-list" role="group" aria-label="Answer choices">'+q.options.map((o,i)=>'<button class="answer-option '+(pick?(o===q.a?'correct':o===pick?'incorrect':''):'')+'" data-action="drill-pick" data-value="'+esc(o)+'" '+(pick?'disabled':'')+'><span class="answer-letter">'+'ABCD'[i]+'</span><span>'+esc(o)+(pick&&o===q.a?'<span class="answer-state">Correct answer</span>':'')+(pick&&o===pick&&o!==q.a?'<span class="answer-state wrong">Your answer</span>':'')+'</span></button>').join('')+'</div><div class="session-footer"><p>'+(pick?(pick===q.a?'Correct.':'Not quite: the answer is '+esc(q.a)+'.'):'Choose an answer to check it instantly.')+'</p>'+(pick?button('drill-next',drill.index===drill.qs.length-1?'See results':'Next question'):'')+'</div></div>';}
function finderScores(){return finder.levels.map(l=>{let score=0;const fits=[],against=[];for(const f of finder.findings){if(!finderPicks.has(f.id))continue;const w=f.w[l.id]||0;score+=w;if(w>=2)fits.push(f.label);else if(w<=-2)against.push(f.label);}return {...l,score,fits,against};}).sort((a,b)=>b.score-a.score||a.against.length-b.against.length);}
function finderResults(){if(!finderPicks.size)return '<div class="finder-empty">'+icon('compass')+'<p>Choose at least one finding. Candidate levels appear here, ranked by how well they explain everything you selected.</p></div>';const ranked=finderScores(),top=ranked[0].score,shown=ranked.filter(l=>l.score>0).slice(0,4);let html='';if(top<=0||!shown.length)html+='<div class="finder-warning"><strong>No single level explains this combination.</strong><p>Consider a multifocal or diffuse process, or re-examine a finding that may be unreliable.</p></div>';else{if(ranked[1]&&ranked[1].score>0&&top-ranked[1].score<=1)html+='<div class="finder-warning"><strong>Close call.</strong><p>Two levels explain these findings almost equally. Find a clue that separates them.</p></div>';html+=shown.map((l,i)=>'<div class="finder-result '+(i===0?'lead':'')+'"><div class="finder-top"><span class="finder-rank">'+(i+1)+'</span><strong>'+esc(l.title)+'</strong><span class="finder-score">'+l.score+' pt'+(l.score===1?'':'s')+'</span></div><div class="progress-line"><span style="width:'+Math.max(6,l.score/top*100)+'%"></span></div>'+(l.fits.length?'<p><b>Fits:</b> '+l.fits.map(esc).join(' · ')+'</p>':'')+(l.against.length?'<p class="against"><b>Argues against:</b> '+l.against.map(esc).join(' · ')+'</p>':'')+'<p class="muted">'+esc(l.test)+'</p><div class="button-row">'+button('topic','Lesson',l.topic,'text-button','book')+button('diagram','Diagram',l.diagram,'text-button','eye')+'</div></div>').join('');}const out=ranked.filter(l=>l.against.length&&l.score<0).slice(-3).reverse();if(out.length)html+='<p class="finder-out"><b>Least likely:</b> '+out.map(l=>esc(l.title)).join(' · ')+'</p>';return html;}
function renderFinder(){return '<div>'+backButton('nav','Learning atlas','learn')+header('PATTERN FINDER','Which level explains everything?','Select the findings you have. Each level gains points for findings it explains and loses points for findings that argue against it.')+'<div class="finder-layout"><section class="finder-picks">'+finder.groups.map(g=>'<fieldset><legend>'+esc(g)+'</legend>'+finder.findings.filter(f=>f.group===g).map(f=>'<button class="finder-chip '+(finderPicks.has(f.id)?'active':'')+'" data-action="finder-toggle" data-value="'+f.id+'" aria-pressed="'+finderPicks.has(f.id)+'"><span class="tick">'+icon('check')+'</span>'+esc(f.label)+'</button>').join('')+'</fieldset>').join('')+'<div class="button-row">'+button('finder-clear','Clear findings','','secondary-button','reset')+'</div></section><section class="finder-output" aria-live="polite"><span class="eyebrow">CANDIDATE LEVELS <span id="finder-count">· '+finderPicks.size+' FINDING'+(finderPicks.size===1?'':'S')+'</span></span><div id="finder-results">'+finderResults()+'</div></section></div><p class="foot-note">A teaching heuristic with hand-set weights, built to practice reasoning, not to diagnose. It assumes one lesion; real patients can have several, and an unreliable finding can mislead any scoring.</p></div>';}
function updateFinder(){document.querySelectorAll('.finder-chip').forEach(b=>{const on=finderPicks.has(b.dataset.value);b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});const r=document.getElementById('finder-results');if(r)r.innerHTML=finderResults();const c=document.getElementById('finder-count');if(c)c.textContent='· '+finderPicks.size+' FINDING'+(finderPicks.size===1?'':'S');}
function empty(title,description,action,label,value='',ico='search'){return `<div class="empty-state">${icon(ico)}<h2>${title}</h2><p>${description}</p><div class="button-row">${button(action,label,value,'primary-button')}</div></div>`;}
function openSheet(title,html){if(sheet.open)sheet.close();sheet.classList.remove('diagram-sheet');sheet.innerHTML=`<div class="sheet-head"><h2 id="sheet-title">${title}</h2><button class="icon-button" data-action="close-sheet" aria-label="Close dialog">${icon('close')}</button></div>${html}`;sheet.showModal();}
function settings(){openSheet('Your study studio',`<div class="setting-row"><label for="theme-setting">Appearance<small>Choose your reading environment</small></label><select id="theme-setting">${['light','dark','system'].map(x=>`<option value="${x}" ${state.theme===x?'selected':''}>${x[0].toUpperCase()+x.slice(1)}</option>`).join('')}</select></div><div class="setting-row"><label for="size-setting">Text size<small>Comfortable, accessible reading</small></label><select id="size-setting"><option value="normal" ${state.size==='normal'?'selected':''}>Standard</option><option value="large" ${state.size==='large'?'selected':''}>Large</option></select></div><div class="setting-row"><div>Study progress<small>Stored only on this device</small></div>${button('reset-dialog','Reset','','text-button','reset')}</div><div class="about-copy"><p><strong>NeuroLocalize · Version ${APP_VERSION}</strong><br>${topics.length} lessons · ${cases.length} cases · ${cards.length} recall cards · ${atlas.length} diagrams · ${drills.length} drill decks</p><p>Designed for medical learners practicing neurological localization. Original, source-linked summaries and synthetic cases; not independently clinician-reviewed or clinically validated.</p><p><strong>Your privacy</strong><br>No account, analytics, advertisements, or app network permission. Progress stays in local app storage. Uninstalling removes it; Android backup is disabled. External references open in your browser.</p><p><strong>Educational use only.</strong> Not a tool for diagnosis, triage, or patient management. Verify clinical decisions against current guidance and qualified supervision.</p><p>Font: Geist, SIL Open Font License. Bundled license included with the app.</p></div>${button('library-dialog','Explore the references','','secondary-button','library')}`);}
function setZoom(z){const img=sheet.querySelector('.diagram-viewport img');if(!img)return;diagramZoom=z;img.style.width=(z*100)+'%';sheet.querySelectorAll('.zoom-button').forEach(b=>{const on=Number(b.dataset.value)===z;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});const d=diagramById[currentDiagram];document.getElementById('diagram-zoom-status').textContent=(z===1?'Fit to screen':z+'× · drag or scroll to explore')+(d?' · '+(atlas.indexOf(d)+1)+' of '+atlas.length:'');}
function updateSearch(){const old=document.getElementById('search-results');const tmp=document.createElement('div');tmp.innerHTML=view==='learn'?renderLearn():view==='cases'?renderCases():view==='atlas'?renderAtlas():renderLibrary();const result=tmp.querySelector('#search-results');if(old&&result)old.replaceWith(result);}
function dispatch(action,value,el){switch(action){
 case 'nav':navigate(value);break;
 case 'settings':settings();break;
 case 'diagram':showDiagram(value);break;
 case 'diagram-scale':setZoom(Number(value)||1);break;
 case 'atlas-group':atlasGroup=value;render({scroll:false});break;
 case 'topic-from-diagram':sheet.close();detailId=value;view='topic';render({focus:true});break;
 case 'finder-toggle':if(finderPicks.has(value))finderPicks.delete(value);else finderPicks.add(value);updateFinder();break;
 case 'drill-start':if(sheet.open)sheet.close();startDrill(value);break;
 case 'drill-pick':if(drill&&!drill.done&&!drill.picks[drill.index]){drill.picks[drill.index]=value;activity('cards');save();render({scroll:false});}break;
 case 'drill-next':if(drill&&drill.picks[drill.index]){if(drill.index<drill.qs.length-1)drill.index++;else{drill.done=true;const pct=Math.round(drill.qs.filter((q,i)=>drill.picks[i]===q.a).length/drill.qs.length*100),old=state.drills[drill.deck];state.drills[drill.deck]={best:Math.max(pct,old?.best||0),last:pct,plays:(old?.plays||0)+1};save();}render({focus:true});}break;
 case 'finder-clear':finderPicks.clear();render({scroll:false});break;
 case 'revisit-misses':{const latest=latestAttempts(true),ids=Object.values(latest).filter(a=>!a.correct).map(a=>a.caseId);if(!ids.length){toast('No missed cases in this edition yet. Nicely done.');break;}startSession(practice.shuffle(ids).slice(0,10));break;}
 case 'close-sheet':sheet.close();break;
 case 'topic':detailId=value;view='topic';render({focus:true});break;
 case 'complete-topic':if(!state.read[value]){state.read[value]=true;activity('lessons');save();toast('Lesson completed. Try its cases to put the pattern into practice.');render({scroll:false});}else toast('You have already completed this lesson.');break;
 case 'topic-cases':topicFilter=value;difficultyFilter='all';taskFilter='all';onlySaved=false;navigate('cases');break;
 case 'learn-filter':learnFilter=value;render({scroll:false});break;
 case 'task-filter':taskFilter=value;render({scroll:false});break;
 case 'dismiss-update':editionUpdated=false;save();render({scroll:false});break;
 case 'saved-filter':onlySaved=!onlySaved;render({scroll:false});break;
 case 'clear-filters':query='';atlasGroup='all';topicFilter='all';difficultyFilter='all';taskFilter='all';onlySaved=false;learnFilter='all';render({scroll:false});break;
 case 'daily':{const latest=latestAttempts(true),unseen=cases.filter(c=>!latest[c.id]);const pool=unseen.length>=5?unseen:cases;startSession(practice.sampleCases(pool,5));break;}
 case 'exam':startSession(practice.sampleCases(cases,10),'exam');break;
 case 'challenge':startSession(practice.sampleCases(cases.filter(c=>c.difficulty==='Advanced'),10),'exam');break;
 case 'case':startSession([value]);break;
 case 'resume':if(sheet.open)sheet.close();if(state.session){view=state.session.complete?'results':'session';selected=null;render({focus:true});}break;
 case 'replace-session':if(pendingSession){sheet.close();const p=pendingSession;pendingSession=null;startSession(p.ids,p.mode,true);}break;
 case 'select-answer':selected=value;document.querySelectorAll('.answer-option').forEach(o=>{o.classList.toggle('selected',o.dataset.value===value);o.setAttribute('aria-pressed',String(o.dataset.value===value));});document.querySelector('[data-action="submit-answer"]').disabled=false;break;
 case 'submit-answer':submitAnswer();break;
 case 'next-case':nextCase();break;
 case 'bookmark':state.bookmarks[value]=!state.bookmarks[value];if(!state.bookmarks[value])delete state.bookmarks[value];save();toast(state.bookmarks[value]?'Case saved to your collection.':'Bookmark removed.');if(view==='session'){el.classList.toggle('saved',!!state.bookmarks[value]);el.setAttribute('aria-pressed',String(!!state.bookmarks[value]));el.setAttribute('aria-label',`${state.bookmarks[value]?'Unsave':'Save'} this case`);}else if(view==='results')el.innerHTML=`${state.bookmarks[value]?'Remove bookmark':'Save this case'}${icon('bookmark')}`;break;
 case 'retry-missed':{const s=state.session;startSession(s.ids.filter(id=>s.answers[id]!==caseById[id].answerId));break;}
 case 'review-start':if(!['review','flash'].includes(view))reviewFilter='all';startFlash(false);break;
 case 'review-all':startFlash(true);break;
 case 'reveal-card':if(flash){flash.revealed=true;render({scroll:false});document.getElementById('flash-answer')?.scrollIntoView({block:'nearest'});}break;
 case 'rate-card':rateCard(value);break;
 case 'library-dialog':sheet.close();navigate('library');break;
 case 'reset-dialog':openSheet('Reset your progress?',`<p class="about-copy">This clears completed lessons, case answers, bookmarks, review schedules, and your study streak on this device. Your appearance settings will stay.</p><div class="button-row">${button('close-sheet','Keep my progress','','secondary-button','')}${button('reset-confirm','Reset all progress','','danger-button','')}</div>`);break;
 case 'reset-confirm':{const theme=state.theme,size=state.size;state=blankState();state.theme=theme;state.size=size;flash=null;selected=null;pendingSession=null;editionUpdated=false;save();sheet.close();navigate('home');toast('Study progress has been reset.');break;}
}}
document.addEventListener('click',event=>{const el=event.target.closest('[data-action]');if(!el||el.disabled)return;dispatch(el.dataset.action,el.dataset.value||'',el);});
document.addEventListener('input',event=>{if(event.target.id==='search'){query=event.target.value;updateSearch();}});
document.addEventListener('change',event=>{const el=event.target;if(el.id==='topic-filter'){topicFilter=el.value;render({scroll:false});}if(el.id==='review-topic-filter'){reviewFilter=el.value;render({scroll:false});}if(el.id==='difficulty-filter'){difficultyFilter=el.value;render({scroll:false});}if(el.id==='theme-setting'){state.theme=el.value;applySettings();save();}if(el.id==='size-setting'){state.size=el.value;applySettings();save();}});
sheet.addEventListener('click',event=>{if(event.target===sheet){const r=sheet.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)sheet.close();}});
let drag=null;
sheet.addEventListener('pointerdown',e=>{const vp=e.target.closest('.diagram-viewport');if(!vp||diagramZoom===1||e.pointerType==='touch')return;drag={vp,x:e.clientX,y:e.clientY,l:vp.scrollLeft,t:vp.scrollTop};vp.setPointerCapture(e.pointerId);vp.classList.add('dragging');});
sheet.addEventListener('pointermove',e=>{if(!drag)return;drag.vp.scrollLeft=drag.l-(e.clientX-drag.x);drag.vp.scrollTop=drag.t-(e.clientY-drag.y);});
sheet.addEventListener('pointerup',()=>{if(drag){drag.vp.classList.remove('dragging');drag=null;}});
sheet.addEventListener('dblclick',e=>{if(e.target.closest('.diagram-viewport'))setZoom(diagramZoom===1?2:1);});
sheet.addEventListener('keydown',e=>{if(!currentDiagram||!sheet.classList.contains('diagram-sheet')||e.target.matches('input,select'))return;const i=atlas.indexOf(diagramById[currentDiagram]);if(e.key==='ArrowRight'){e.preventDefault();showDiagram(atlas[(i+1)%atlas.length].id);}if(e.key==='ArrowLeft'){e.preventDefault();showDiagram(atlas[(i-1+atlas.length)%atlas.length].id);}if(e.key==='+'||e.key==='='){setZoom(Math.min(3,diagramZoom+1));}if(e.key==='-'){setZoom(Math.max(1,diagramZoom-1));}});
window.neuroBack=()=>{if(sheet.open){sheet.close();return true;}if(view==='topic'||view==='atlas'||view==='finder'){navigate('learn');return true;}if(view==='session'||view==='results'){navigate('cases');return true;}if(view==='flash'||view==='drills'){navigate('review');return true;}if(view==='drill'){navigate('drills');return true;}if(view!=='home'){navigate('home');return true;}return false;};
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!sheet.open)window.neuroBack();});
document.getElementById('brand-icon').innerHTML=icon('brain');document.getElementById('settings-button').innerHTML=icon('settings');
window.NeuroLocalize={topics,cases,cards,sources,atlas,finder,drills,finderScores:ids=>{const keep=new Set(finderPicks);finderPicks=new Set(ids);const r=finderScores();finderPicks=keep;return r;},getState:()=>JSON.parse(JSON.stringify(state)),getView:()=>view,dateKey,reviewInterval};
if(editionUpdated)save();
render();
})();
