'use strict';
/* NeuroLocalize 1.6: lesson deep dives (bedside sequence, comparison table, worked example, extra traps)
   and a glossary. Original teaching summaries of standard neuroanatomy; not clinical guidance. */
window.NL_DEEP = {
 approach: {
  exam: ['Ask exactly what the person means by weak, numb or dizzy, and when it started.', 'Map the distribution: one limb, one side, both legs, distal, proximal or patchy.', 'Check for upper versus lower motor neuron signs: tone, reflexes, plantar response, wasting.', 'Add a second system: sensation, cranial nerves, language, vision or coordination.', 'State one level that explains everything, then name the finding that would prove you wrong.'],
  compare: {title: 'Three patterns of involvement', head: ['Pattern', 'Usually means', 'Think of'], rows: [['Focal', 'One lesion at one level', 'Stroke, compression, a single nerve'], ['Multifocal', 'Several separate lesions', 'Inflammatory or vascular disease, multiple nerves'], ['Diffuse, symmetric', 'A system-wide process', 'Polyneuropathy, myopathy, metabolic or toxic causes']]},
  example: {case: 'Weakness of the right hand and face with trouble finding words, starting suddenly.', steps: ['Face and hand on the same side with language difficulty point above the brainstem.', 'Language involvement adds a cortical sign, usually from the left hemisphere.', 'Sudden onset suggests a vascular mechanism, but the level comes first.'], answer: 'Left frontal cortex and its nearby language network.'},
  traps: ['Stopping at the first level that fits, without testing one finding that does not.', 'Treating "dizzy" or "numb" as a single symptom before clarifying what the person feels.'],
  figs: ['neuraxis', 'weakness-flow', 'time-course', 'body-patterns']
 },
 motor: {
  exam: ['Inspect for wasting and fasciculation at rest.', 'Test tone with slow and fast passive movement; feel for a catch.', 'Grade power in groups: shoulder, elbow, wrist, fingers, hip, knee, ankle.', 'Test reflexes on both sides and compare them, then the plantar responses.', 'Look for drift with arms held out and eyes closed.'],
  compare: {title: 'Patterns of weakness', head: ['Distribution', 'Typical level', 'Supporting sign'], rows: [['Face, arm and leg, one side', 'Opposite hemisphere or brainstem', 'Brisk reflexes, extensor plantar'], ['Both legs, arms spared', 'Thoracic cord (or parasagittal)', 'Sensory level, bladder change'], ['One myotome', 'Nerve root', 'Matching reflex and dermatome'], ['Proximal, symmetric', 'Muscle or junction', 'Sensation normal']]},
  example: {case: 'Both legs weak with brisk knee and ankle reflexes; arms normal; numb below the umbilicus.', steps: ['Upper motor neuron signs in both legs only place the lesion in the cord below the arms.', 'A sensory level at the umbilicus marks about T10 on the skin.', 'The cord lesion is at or above that level.'], answer: 'Thoracic spinal cord at or above T10.'},
  traps: ['Calling weakness "upper motor neuron" from brisk reflexes alone; check plantars and tone too.', 'Forgetting that the cord level can be higher than the sensory level suggests.'],
  figs: ['umn-lmn', 'motor', 'reflex-arc']
 },
 cortex: {
  exam: ['Listen to spontaneous speech, then test naming, repetition, comprehension, reading and writing.', 'Test for neglect: line bisection, cancellation, or double simultaneous touch.', 'Test cortical sensation: number writing on the palm, object recognition by touch, two-point discrimination.', 'Check visual fields by confrontation in each quadrant.', 'Ask the person to mime using a tool to look for apraxia.'],
  compare: {title: 'Hemisphere clues', head: ['Finding', 'Usually points to', 'Note'], rows: [['Aphasia', 'Dominant (usually left) hemisphere', 'Fluency and repetition refine the site'], ['Neglect of the left side', 'Non-dominant (usually right) parietal', 'Can coexist with normal strength'], ['Astereognosis, agraphesthesia', 'Opposite parietal cortex', 'Requires intact primary sensation'], ['Homonymous field cut', 'Opposite temporal, parietal or occipital', 'Superior or inferior quadrant matters']]},
  example: {case: 'A person ignores food on the left of the plate and denies any problem; strength is near normal.', steps: ['Ignoring one side with unawareness is spatial neglect.', 'Left neglect usually arises from the right hemisphere, often parietal.', 'Normal strength makes a large motor lesion less likely.'], answer: 'Right parietal cortex.'},
  traps: ['Mistaking aphasia for confusion; test naming and comprehension separately.', 'Assuming a field cut is ocular without checking both eyes together.'],
  figs: ['cortex', 'aphasia-tree', 'vascular']
 },
 subcortex: {
  exam: ['Compare face, arm and leg strength: are they equally affected?', 'Look carefully for cortical signs: language, neglect, field cut.', 'Test all sensory modalities on both sides of the body.', 'Check for involuntary movements such as flinging or writhing.'],
  compare: {title: 'Cortex or deep pathway?', head: ['Feature', 'Cortical lesion', 'Deep (capsular) lesion'], rows: [['Face, arm, leg', 'Often uneven', 'Often equal'], ['Language or neglect', 'May be present', 'Usually absent'], ['Sensation', 'Cortical modalities affected', 'Can be purely motor or purely sensory'], ['Field cut', 'Common with large lesions', 'Only if the optic radiation is involved']]},
  example: {case: 'Sudden equal weakness of the left face, arm and leg; speech, sensation and fields normal.', steps: ['Equal face, arm and leg weakness suggests fibres packed close together.', 'No cortical or sensory signs argues against a large cortical lesion.', 'Contralateral to the left-sided weakness is the right hemisphere.'], answer: 'Right internal capsule (posterior limb) or ventral pons.'},
  traps: ['Labelling every pure motor stroke as capsular; the pons can produce the same pattern.', 'Missing thalamic sensory loss because strength is normal.'],
  figs: ['compact', 'vascular']
 },
 brainstem: {
  exam: ['Examine every cranial nerve, especially eye movements, facial sensation and swallowing.', 'Look for crossed findings: face on one side, body on the other.', 'Test limb coordination and gait for cerebellar involvement.', 'Check pupils and lids for Horner syndrome.', 'Test both pain and vibration on the body.'],
  compare: {title: 'Classic brainstem patterns', head: ['Pattern', 'Level and side', 'Key nerve'], rows: [['III palsy + opposite hemiparesis', 'Medial midbrain', 'III'], ['VI or VII palsy + opposite hemiparesis', 'Ventral pons', 'VI, VII'], ['XII palsy + opposite hemiparesis', 'Medial medulla', 'XII'], ['Face pain loss, Horner, ataxia + opposite body pain loss', 'Lateral medulla', 'V (spinal), IX, X']]},
  example: {case: 'Left facial numbness to pin, hoarse voice, left Horner, and right-sided body pain loss.', steps: ['Crossed face and body sensory loss means the brainstem.', 'Hoarseness (nucleus ambiguus) and Horner are lateral structures.', 'The facial findings mark the side of the lesion.'], answer: 'Left lateral medulla.'},
  traps: ['Expecting every classical sign; partial syndromes are common.', 'Forgetting that a cranial nerve can be damaged outside the brainstem.'],
  figs: ['brainstem-rule', 'crossed', 'horner']
 },
 cranial: {
  exam: ['II: acuity, fields, pupils and fundi.', 'III, IV, VI: eye movements in all directions and a cover test for diplopia.', 'V and VII: facial sensation, corneal reflex and facial strength including forehead.', 'VIII: whisper test and, when relevant, vestibular tests.', 'IX, X, XII: palate, swallow, voice and tongue protrusion.'],
  compare: {title: 'Facial weakness: central or peripheral?', head: ['Feature', 'Central (above nucleus)', 'Peripheral (nucleus or nerve)'], rows: [['Forehead', 'Largely spared', 'Weak'], ['Eye closure', 'Usually good', 'Weak'], ['Side vs lesion', 'Opposite side', 'Same side'], ['Associated signs', 'Arm weakness, aphasia', 'Hearing, taste or tear changes']]},
  example: {case: 'Sudden inability to wrinkle the right forehead or close the right eye; arm strength normal.', steps: ['Forehead and eye closure weakness indicates a peripheral pattern.', 'A peripheral lesion is on the same side as the weakness.', 'No limb or other cranial signs suggests the nerve outside the brainstem.'], answer: 'Right facial nerve (peripheral).'},
  traps: ['Calling every facial palsy peripheral without checking the forehead.', 'Over-interpreting a sixth nerve palsy: raised intracranial pressure can cause it without a lesion on that nerve.'],
  figs: ['cranial', 'facial', 'cavernous-sinus', 'gaze-circuit']
 },
 eyes: {
  exam: ['Compare pupil sizes in bright and dim light, then perform the swinging light test.', 'Test pursuit in an H pattern and ask where double vision is worst.', 'Cover each eye to see which image disappears.', 'Test saccades and look for nystagmus.', 'Check lids for ptosis and fatigability.'],
  compare: {title: 'Ptosis with a pupil change', head: ['Finding', 'Third nerve', 'Horner syndrome'], rows: [['Pupil', 'Large, poorly reactive', 'Small, reacts to light'], ['Ptosis', 'Often marked', 'Mild'], ['Eye movement', 'Down and out', 'Normal'], ['Worse in', 'Bright light (anisocoria)', 'Dim light (anisocoria)']]},
  example: {case: 'Double vision worst looking down and to the left; the right eye sits slightly higher.', steps: ['Vertical diplopia worse looking down suggests a depressor muscle.', 'Worse looking down and to the left implicates the right superior oblique, which depresses in adduction.', 'The superior oblique is supplied by IV.'], answer: 'Right fourth nerve (trochlear) palsy.'},
  traps: ['Missing a myasthenic pattern because the pupils are normal.', 'Attributing a large pupil to drops or trauma before excluding a third nerve palsy.'],
  figs: ['eye-muscles', 'pupil-reflex', 'gaze-circuit', 'cavernous-sinus']
 },
 cord: {
  exam: ['Search for a sensory level with pin, moving upward from the feet on the trunk.', 'Compare pain and vibration on each side.', 'Test reflexes above and below the suspected level.', 'Ask about bladder and bowel change; check saddle sensation.', 'Look for a band of pain or lower motor signs at the level of the lesion.'],
  compare: {title: 'Cord syndromes', head: ['Syndrome', 'Lost', 'Spared'], rows: [['Anterior cord', 'Strength, pain, temperature', 'Vibration, position'], ['Posterior cord', 'Vibration, position', 'Strength often, pain'], ['Central cord', 'Arms more than legs; cape-like pain loss', 'Sacral sensation often'], ['Hemicord', 'Same-side strength and vibration', 'Opposite-side vibration']]},
  example: {case: 'Weak right leg, loss of vibration in the right leg, loss of pain in the left leg.', steps: ['Strength and vibration lost on one side with pain lost on the other is dissociated loss.', 'This fits damage to one half of the cord.', 'Motor and vibration loss mark the lesion side.'], answer: 'Right hemicord (Brown-Séquard pattern).'},
  traps: ['Missing a cord lesion because the arms are normal; check the trunk for a level.', 'Assuming normal reflexes exclude an acute cord lesion.'],
  figs: ['cord-syndromes', 'hemicord', 'conus-cauda', 'sensory-pathways']
 },
 roots: {
  exam: ['Ask about radiating pain and what posture or cough makes it worse.', 'Test muscles that share the root but use different nerves.', 'Test the reflex for that root.', 'Map sensory change against dermatome landmarks.', 'Look for a straight-leg raise or neck movement that reproduces the pain.'],
  compare: {title: 'Common radiculopathies', head: ['Root', 'Weakness', 'Reflex / sensation'], rows: [['C6', 'Elbow flexion, wrist extension', 'Brachioradialis; thumb'], ['C7', 'Elbow and finger extension', 'Triceps; middle finger'], ['L5', 'Toe and foot extension, hip abduction', 'None reliable; top of the foot'], ['S1', 'Plantar flexion', 'Ankle; outer foot and sole']]},
  example: {case: 'Back pain shooting down the leg, weak great-toe extension and hip abduction, normal ankle reflex.', steps: ['Toe extension and hip abduction share L5 but use different nerves.', 'A normal ankle reflex makes S1 less likely.', 'Radiating pain supports a root.'], answer: 'L5 radiculopathy.'},
  traps: ['Expecting a full dermatomal band; overlap makes single-root loss small.', 'Diagnosing a root lesion from pain alone without matching weakness or reflex change.'],
  figs: ['root-signatures', 'dermatome-landmarks', 'reflex-arc']
 },
 plexus: {
  exam: ['Test muscles supplied by different nerves in the affected limb.', 'Check whether deficits span more than one root.', 'Test sensation in each nerve and dermatome territory.', 'Look for Horner syndrome with a lower brachial plexus pattern.', 'Ask about trauma, radiation, cancer or severe preceding pain.'],
  compare: {title: 'Upper or lower brachial plexus?', head: ['Feature', 'Upper trunk (C5–C6)', 'Lower trunk (C8–T1)'], rows: [['Weak', 'Shoulder abduction, elbow flexion', 'Hand muscles'], ['Reflex', 'Biceps reduced', 'Usually normal arm reflexes'], ['Sensory loss', 'Lateral arm', 'Medial forearm and hand'], ['Extra sign', 'Arm hangs internally rotated', 'Possible Horner syndrome']]},
  example: {case: 'Weak shoulder abduction, elbow flexion and external rotation after a fall onto the shoulder.', steps: ['Several muscles from axillary, musculocutaneous and suprascapular nerves are weak.', 'All share C5–C6.', 'Trauma that widens the neck–shoulder angle stretches the upper trunk.'], answer: 'Upper trunk of the brachial plexus.'},
  traps: ['Calling a plexopathy a mononeuropathy because one muscle is weakest.', 'Ignoring a Horner syndrome that points to a proximal lower plexus or root lesion.'],
  figs: ['brachial-plexus', 'lumbosacral', 'peripheral']
 },
 leg: {
  exam: ['Test hip flexion, adduction and abduction, knee extension and flexion.', 'Test ankle dorsiflexion, plantar flexion, inversion and eversion separately.', 'Check knee and ankle reflexes on both sides.', 'Map sensory change: medial leg, lateral leg, top of the foot, sole.', 'Look at the back for tenderness or pain on movement.'],
  compare: {title: 'Leg nerve lesions', head: ['Nerve', 'Weak', 'Sensory loss'], rows: [['Femoral', 'Knee extension (knee reflex lost)', 'Front of thigh, medial leg'], ['Obturator', 'Hip adduction', 'Medial thigh'], ['Common fibular', 'Dorsiflexion and eversion', 'Lateral leg, top of foot'], ['Tibial', 'Plantar flexion and inversion', 'Sole']]},
  example: {case: 'Foot drop after crossing the legs for hours; inversion and hip abduction normal; numb top of foot.', steps: ['Dorsiflexion is weak but inversion (tibial) and hip abduction (gluteal) are spared.', 'Sensory change on the top of the foot fits the fibular nerve.', 'Compression at the fibular head is a common site.'], answer: 'Common fibular nerve at the fibular head.'},
  traps: ['Diagnosing a fibular palsy without testing inversion and hip abduction.', 'Missing a femoral neuropathy when the knee buckles but the patient walks.'],
  figs: ['lumbosacral', 'dermatome-landmarks']
 },
 nerves: {
  exam: ['Test one muscle supplied by each major nerve in the affected limb.', 'Map sensory loss against nerve territories, including whether the ring finger splits.', 'Tap over common compression sites for tingling.', 'Compare with the other side.', 'Check reflexes: a nerve lesion reduces only reflexes it carries.'],
  compare: {title: 'Hand nerve lesions', head: ['Nerve', 'Weakness', 'Sensory clue'], rows: [['Median (wrist)', 'Thumb abduction', 'Thumb to radial ring, palm side'], ['Ulnar (elbow)', 'Finger spreading, grip', 'Little finger, split ring'], ['Radial (arm)', 'Wrist and finger extension', 'Back of first web space'], ['C8 root', 'Hand muscles across nerves', 'Whole ring and little finger, medial forearm']]},
  example: {case: 'Numb little finger and half the ring finger, weak finger spreading, normal thumb abduction.', steps: ['Finger spreading uses ulnar muscles; thumb abduction (median) is spared.', 'Sensory loss splits the ring finger, a nerve border.', 'A C8 root lesion would weaken median muscles too.'], answer: 'Ulnar neuropathy.'},
  traps: ['Calling every hand numbness carpal tunnel without mapping the territory.', 'Missing a polyneuropathy when symptoms start in the feet first.'],
  figs: ['hand-nerves', 'peripheral', 'body-patterns']
 },
 nmj: {
  exam: ['Ask whether weakness worsens through the day or with use.', 'Test sustained upgaze for ptosis and a cover test for diplopia.', 'Test neck flexion and proximal limb strength after repetition.', 'Check reflexes before and after brief maximal effort.', 'Ask about dry mouth, constipation or dizziness on standing.'],
  compare: {title: 'Junction disorders', head: ['Feature', 'Myasthenia gravis', 'Lambert–Eaton'], rows: [['Site', 'Postsynaptic receptors', 'Presynaptic calcium channels'], ['Typical start', 'Eyes, bulbar muscles', 'Proximal legs'], ['Reflexes', 'Normal', 'Reduced, may improve after effort'], ['Autonomic', 'No', 'Dry mouth common']]},
  example: {case: 'Drooping eyelids and double vision that worsen by evening; strength and reflexes otherwise normal.', steps: ['Fatigable, fluctuating eye muscle weakness suggests the junction.', 'Normal reflexes and no autonomic symptoms favour a postsynaptic disorder.', 'Pupils are spared.'], answer: 'Neuromuscular junction, postsynaptic (myasthenia pattern).'},
  traps: ['Missing fatigability because the examination was brief.', 'Ignoring sensory loss: junction disorders spare sensation, so its presence points to another level.'],
  figs: ['motor-unit', 'nmj-compare']
 },
 muscle: {
  exam: ['Test neck flexion and proximal limb strength: rising from a chair, lifting arms overhead.', 'Look for a waddling gait or using hands to climb up the legs.', 'Check for wasting, hypertrophy or tenderness.', 'Confirm sensation is normal and reflexes are preserved.', 'Ask about dark urine, rash, drugs and family history.'],
  compare: {title: 'Muscle or nerve?', head: ['Feature', 'Myopathy', 'Neuropathy'], rows: [['Distribution', 'Proximal, symmetric', 'Distal first'], ['Sensation', 'Normal', 'Often affected'], ['Reflexes', 'Kept until late', 'Reduced early'], ['Fasciculation', 'Absent', 'May occur']]},
  example: {case: 'Difficulty climbing stairs and combing hair over months; sensation and reflexes normal.', steps: ['Symmetric proximal weakness with normal sensation is a motor pattern.', 'Preserved reflexes and no fatigability point away from the junction.', 'Slow progression fits a myopathy.'], answer: 'Muscle (myopathy pattern).'},
  traps: ['Assuming proximal weakness always means myopathy; junction and motor neuron disease can mimic it.', 'Missing distal myopathies that look like neuropathies.'],
  figs: ['motor-unit', 'body-patterns', 'umn-lmn']
 },
 cerebellum: {
  exam: ['Finger–nose and heel–shin testing for dysmetria and intention tremor.', 'Rapid alternating movements for dysdiadochokinesia.', 'Stance with feet together, then tandem gait.', 'Eye movements for nystagmus and saccadic pursuit.', 'Romberg test to separate sensory from cerebellar ataxia.'],
  compare: {title: 'Ataxia: where from?', head: ['Feature', 'Cerebellar', 'Sensory'], rows: [['Eyes closed', 'Little change', 'Much worse (Romberg)'], ['Position sense', 'Normal', 'Reduced'], ['Reflexes', 'Usually normal', 'Often reduced'], ['Eye movements', 'Nystagmus possible', 'Normal']]},
  example: {case: 'Overshooting with the right finger–nose test and clumsy right hand; strength and sensation normal.', steps: ['Limb dysmetria with normal strength and position sense suggests the cerebellum.', 'Limb ataxia is usually ipsilateral to a cerebellar hemisphere lesion.', 'Gait is less affected than the limb.'], answer: 'Right cerebellar hemisphere.'},
  traps: ['Calling ataxia cerebellar without testing position sense.', 'Expecting cerebellar limb signs on the opposite side, as with cortical lesions.'],
  figs: ['coordination', 'sensory-pathways']
 },
 vision: {
  exam: ['Test acuity in each eye separately.', 'Confrontation fields in all four quadrants of each eye.', 'Check pupils, including the swinging light test.', 'Compare the defect in the two eyes: is it homonymous and congruous?', 'Look for associated cortical signs such as neglect or alexia.'],
  compare: {title: 'Where is the field defect from?', head: ['Defect', 'Site', 'Clue'], rows: [['One eye', 'Retina or optic nerve', 'Afferent pupil defect'], ['Bitemporal', 'Chiasm', 'Often pituitary region'], ['Homonymous, upper quadrant', 'Temporal lobe', 'Meyer loop'], ['Homonymous, macula spared', 'Occipital cortex', 'Congruous defect']]},
  example: {case: 'Missing the upper left quarter of vision in both eyes; acuity normal.', steps: ['The defect is in both eyes on the same side: homonymous, so behind the chiasm.', 'Upper quadrant loss implicates the Meyer loop.', 'Left field loss means the right pathway.'], answer: 'Right temporal lobe (Meyer loop).'},
  traps: ['Assuming a field defect noticed in one eye is monocular without testing the other.', 'Missing bitemporal loss because each eye compensates for the other.'],
  figs: ['vision', 'field-defects', 'pupil-reflex']
 },
 sensory: {
  exam: ['Test pin or cold and vibration or position separately.', 'Start distally and move proximally to find a border.', 'Compare both sides and map any level on the trunk.', 'Test cortical sensation if primary sensation is intact.', 'Perform the Romberg test.'],
  compare: {title: 'Which system is affected?', head: ['Modality', 'Pathway', 'Crosses'], rows: [['Pain, temperature', 'Spinothalamic', 'Within a few cord segments'], ['Vibration, position', 'Dorsal column', 'In the medulla'], ['Face pain', 'Spinal trigeminal', 'In the medulla, after descending'], ['Discriminative touch', 'Dorsal column to cortex', 'In the medulla']]},
  example: {case: 'Loss of pain and temperature over both shoulders and arms; vibration and strength normal.', steps: ['Selective pain loss in a cape distribution spares the dorsal columns.', 'Crossing pain fibres near the centre of the cord are affected first.', 'The cervical segments map to the shoulders and arms.'], answer: 'Central cervical cord (syrinx-like pattern).'},
  traps: ['Testing only light touch, which travels in more than one pathway.', 'Missing a level because testing started on the trunk instead of the feet.'],
  figs: ['sensory-pathways', 'dermatome-landmarks', 'hemicord']
 }
};

window.NL_GLOSSARY = [
 ['Agraphesthesia', 'Inability to recognise numbers or letters traced on the skin despite intact primary sensation; a cortical sensory sign.'],
 ['Anosognosia', 'Unawareness of one’s own deficit, often with non-dominant parietal lesions.'],
 ['Anterior horn', 'Grey matter of the spinal cord containing lower motor neuron cell bodies.'],
 ['Aphasia', 'An acquired disorder of language production or comprehension.'],
 ['Apraxia', 'Inability to carry out learned movements on command despite adequate strength and understanding.'],
 ['Astereognosis', 'Inability to recognise an object by touch alone despite intact primary sensation.'],
 ['Ataxia', 'Incoordination of movement not explained by weakness.'],
 ['Babinski sign', 'Extensor plantar response: upward movement of the great toe on stroking the sole; an upper motor neuron sign.'],
 ['Bitemporal hemianopia', 'Loss of the outer half of the visual field in both eyes, typical of a chiasmal lesion.'],
 ['Brown-Séquard pattern', 'Hemicord lesion: same-side weakness and vibration loss with opposite-side pain loss.'],
 ['Cauda equina', 'The bundle of lumbar and sacral nerve roots below the end of the spinal cord.'],
 ['Clonus', 'Rhythmic involuntary contractions after a sudden stretch; an upper motor neuron sign.'],
 ['Congruous defect', 'Homonymous field defects that are nearly identical in both eyes; suggests a posterior lesion.'],
 ['Conus medullaris', 'The tapered lower end of the spinal cord, usually near L1–L2.'],
 ['Corticobulbar', 'Fibres from the cortex to cranial nerve motor nuclei.'],
 ['Corticospinal tract', 'The main descending motor pathway from cortex to spinal cord; most fibres cross in the medulla.'],
 ['Decussation', 'A crossing of fibres from one side of the nervous system to the other.'],
 ['Dermatome', 'The area of skin supplied by a single spinal root.'],
 ['Diplopia', 'Double vision; binocular diplopia resolves when either eye is covered.'],
 ['Dorsal column', 'Spinal cord pathway carrying vibration, position and discriminative touch; crosses in the medulla.'],
 ['Dorsal root ganglion', 'Cluster of sensory neuron cell bodies next to the spinal cord.'],
 ['Dysarthria', 'Impaired articulation of speech with normal language.'],
 ['Dysdiadochokinesia', 'Difficulty performing rapid alternating movements; a cerebellar sign.'],
 ['Dysmetria', 'Overshooting or undershooting a target; a cerebellar sign.'],
 ['Fasciculation', 'Visible twitching of a small group of muscle fibres; a lower motor neuron sign.'],
 ['Fatigability', 'Weakness that increases with repeated or sustained use; typical of junction disorders.'],
 ['Genu', 'The bend of the internal capsule, carrying corticobulbar fibres.'],
 ['Hemianopia', 'Loss of half of the visual field.'],
 ['Homonymous', 'Affecting the same side of the visual field in both eyes; indicates a lesion behind the chiasm.'],
 ['Horner syndrome', 'Mild ptosis and a small pupil on one side from interruption of the sympathetic pathway.'],
 ['Hyperreflexia', 'Abnormally brisk reflexes; usually an upper motor neuron sign.'],
 ['Internal capsule', 'Compact white matter between the thalamus, caudate and lentiform nucleus.'],
 ['Internuclear ophthalmoplegia', 'Failure of adduction on lateral gaze from a lesion of the medial longitudinal fasciculus.'],
 ['Lateral geniculate nucleus', 'Thalamic relay for vision between the optic tract and optic radiation.'],
 ['Lower motor neuron', 'The anterior horn cell or cranial motor nucleus and its axon to muscle.'],
 ['Medial lemniscus', 'Brainstem continuation of the dorsal column pathway after it crosses.'],
 ['Medial longitudinal fasciculus', 'Brainstem pathway linking eye movement nuclei for conjugate gaze.'],
 ['Meyer loop', 'Inferior optic radiation fibres in the temporal lobe carrying the upper visual field.'],
 ['Miosis', 'A small pupil.'],
 ['Mononeuropathy', 'Damage to a single peripheral nerve.'],
 ['Myotome', 'The group of muscles supplied mainly by a single spinal root.'],
 ['Neglect', 'Failure to attend to one side of space or the body, usually the left after right hemisphere lesions.'],
 ['Nystagmus', 'Involuntary rhythmic eye movements.'],
 ['Plexopathy', 'Damage to a nerve plexus, affecting several nerves and roots in one limb.'],
 ['Polyneuropathy', 'Diffuse damage to peripheral nerves, typically length-dependent and symmetric.'],
 ['PPRF', 'Paramedian pontine reticular formation, which generates horizontal saccades.'],
 ['Pronator drift', 'Downward drift and pronation of an outstretched arm with eyes closed; a subtle upper motor neuron sign.'],
 ['Ptosis', 'Drooping of the upper eyelid.'],
 ['Quadrantanopia', 'Loss of one quarter of the visual field.'],
 ['Radiculopathy', 'Dysfunction of a spinal nerve root.'],
 ['RAPD', 'Relative afferent pupillary defect: reduced response to light in one eye from an afferent lesion.'],
 ['Romberg sign', 'Loss of balance with feet together when the eyes close; indicates impaired position sense.'],
 ['Saddle anaesthesia', 'Sensory loss over the perineum and buttocks; suggests a conus or cauda equina lesion.'],
 ['Sensory level', 'A border on the trunk below which sensation is reduced; suggests a spinal cord lesion.'],
 ['Spasticity', 'Velocity-dependent increase in muscle tone; an upper motor neuron sign.'],
 ['Spinothalamic tract', 'Spinal pathway for pain and temperature; crosses near its entry level.'],
 ['Upper motor neuron', 'Neurons and pathways from the cortex down to the anterior horn or cranial motor nuclei.'],
 ['Vermis', 'The midline part of the cerebellum, concerned with posture and gait.']
];

/* 1.8: a deeper paragraph for each lesson section, in section order. */
window.NL_LESSON_MORE = {
 approach: ['Separate symptoms from signs. "Weak" may mean clumsy, tired or numb, and "dizzy" may mean vertigo, light-headedness or imbalance. Pin down which body parts are affected and whether both sides are involved, because one level must explain the whole distribution.', 'A useful hypothesis names one level and one side. Test it actively: if a cortical lesion is proposed, look for language, neglect or a field cut; if a cord lesion, search for a sensory level. Any finding the hypothesis cannot explain means either a second lesion or the wrong level.', 'Mechanism comes from the time course: sudden, evolving over days, progressive over months, or episodic. Keep it separate from location. A sudden onset tells you about cause, not where the lesion is.'],
 motor: ['Upper motor neurons run from the motor cortex through the internal capsule, brainstem and spinal cord to the anterior horn cells. Damage removes their inhibitory control over spinal reflexes, so tone rises (spasticity), reflexes become brisk and may spread, and the plantar response turns extensor. Weakness tends to affect arm extensors and leg flexors more (pyramidal pattern).', 'Lower motor neurons are the anterior horn cells and their axons in roots and nerves. Damage removes the reflex arc and the muscle\'s nerve supply, so reflexes fall, tone is low, the muscle wastes and may twitch (fasciculations). The distribution follows a root, nerve or segment rather than a whole side.', 'In the first hours to days after a severe brain or cord lesion, the affected limbs can be floppy with absent reflexes (shock). Spasticity and brisk reflexes appear later. A flaccid limb with a sensory level or extensor plantar is still a central lesion.'],
 cortex: ['Language lives in a left-hemisphere network in most people, including many left-handers. Fluency, comprehension, repetition and naming are tested separately because each points to a different part of the network. Dysarthria is a problem of articulation, not language, and can arise anywhere from cortex to muscle.', 'Neglect is a failure to attend to one side, usually the left after right parietal or frontal damage. Primary sensation and vision may be intact, but the person ignores one side, especially when both sides compete (extinction). Cortical sensory signs such as astereognosis and agraphesthesia only count when basic sensation is normal.', 'Each lobe has a signature: frontal for planning, behaviour and the motor strip; parietal for sensation, space and praxis; temporal for memory, hearing and comprehension, plus the upper visual field fibres; occipital for vision. A deficit from one of these, together with motor or sensory signs, places the lesion in the hemisphere.'],
 subcortex: ['In the internal capsule, motor fibres for the face (at the genu) and for the arm and leg (in the posterior limb) lie close together. A small lesion can therefore weaken the whole opposite side evenly, without the language, attention or field signs that larger cortical lesions bring.', 'The thalamus is the relay for all ascending sensation to the cortex. A lesion in its ventral posterior nuclei can remove pain, temperature and vibration over the whole opposite side, including the face, and later may cause pain. Comparing face and body helps: the face relays in a separate, more medial nucleus.', 'A pure motor hemiparesis can come from the internal capsule or the ventral pons, and a pure sensory stroke from the thalamus or nearby capsule. The examination proves side and pathway; imaging is what fixes the exact site.'],
 brainstem: ['Cranial nerve nuclei and fibres sit next to long tracts that have not yet crossed (or, for sensation, have already crossed). A single lesion therefore produces a cranial nerve sign on its own side and limb signs on the opposite side. The cranial nerve tells you the side of the lesion and its level.', 'Use the nerve involved: III or IV for the midbrain, V to VIII for the pons, IX to XII for the medulla. Medial lesions involve motor nuclei (III, IV, VI, XII), the pyramids and the medial lemniscus; lateral lesions involve sensory and autonomic structures and cerebellar connections.', 'Facial pain fibres descend in the spinal trigeminal tract before crossing, while body pain fibres crossed in the spinal cord. In the lower brainstem these two pathways lie next to each other but carry opposite sides, so a lateral lesion causes same-side facial loss and opposite-side body loss.'],
 cranial: ['A cranial nerve can be damaged inside the brainstem, at the skull base, in the cavernous sinus or orbit, or along its course. Brainstem lesions usually bring long-tract signs; skull base and sinus lesions usually involve several nerves together. Isolated single nerve palsies are often outside the brainstem.', 'Upper-face motor neurons receive input from both hemispheres, so a lesion above the facial nucleus mostly spares the forehead and eye closure. A lesion of the nucleus or nerve weakens the whole face on that side, and may also affect taste, tear production or sound sensitivity depending on where the nerve is damaged.', 'The corneal reflex has a trigeminal (V1) afferent and a facial (VII) efferent to both eyes. Touching one cornea normally makes both eyes blink: no blink from either eye points to the afferent side; one eye failing to blink whichever side is touched points to that eye\'s facial nerve.'],
 cord: ['A sensory level is a horizontal border on the trunk below which sensation changes. It points to the cord, but the lesion can be several segments above the level you find, so imaging should cover above it. The cord ends near the L1–L2 vertebrae, so cord segments and vertebral levels drift apart lower down.', 'At one level, motor fibres and dorsal column fibres serve the same side of the body, while spinothalamic fibres serve the opposite side because they crossed near entry. That is why one-sided cord damage splits the modalities. Partial lesions give partial versions of this pattern.', 'Below the conus, the cauda equina is made of roots, so lesions there produce lower motor neuron signs and root pain. A conus lesion can mix upper and lower motor neuron signs. Both can cause saddle numbness and bladder or bowel change, which need urgent assessment.'],
 roots: ['Each root supplies a myotome (muscles), a dermatome (skin) and often a reflex. A root lesion therefore causes radiating pain, weakness of muscles that may belong to several different nerves, a reduced matching reflex and sensory change in a band, though dermatome overlap often makes the sensory loss small.', 'C7 supplies triceps, wrist flexors and finger extensors and carries the triceps reflex; C5–C6 carry the biceps and brachioradialis reflexes; L3–L4 the knee reflex; S1 the ankle reflex. L5 has no reliable routine reflex, so muscle testing carries more weight there.', 'The most useful trick is to test two muscles from the same root that use different nerves, for example tibialis anterior (fibular) and tibialis posterior (tibial) for L5. If both are weak, the root is more likely than either nerve. Sensory nerve studies stay normal in root lesions because the lesion is proximal to the dorsal root ganglion.'],
 plexus: ['A plexus is where roots mix and regroup into nerves. Lesions here affect several nerves and more than one root in one limb, often with pain. Because they lie beyond the dorsal root ganglia, sensory nerve responses are reduced, which helps separate them from root lesions.', 'In the brachial plexus, upper trunk lesions (C5–C6) weaken shoulder abduction and elbow flexion; lower trunk lesions (C8–T1) weaken the hand and numb the medial forearm; posterior cord lesions combine axillary and radial weakness. In the lumbosacral plexus, lumbar lesions combine femoral and obturator territories, and sacral lesions combine gluteal and sciatic territories.', 'Electrodiagnostic studies show which muscles and sensory nerves are involved and whether paraspinal muscles are spared, which places the lesion beyond the roots. Imaging looks for compression, infiltration or inflammation along the plexus.'],
 nerves: ['A mononeuropathy follows one nerve\'s motor and sensory map below the lesion. Knowing where each branch leaves the nerve lets you place the lesion along its course: for example, a numb dorsal ulnar hand means the ulnar lesion is above the wrist, because that branch leaves before Guyon canal.', 'Foot drop is a good example of separating nerve from root. The common fibular nerve supplies dorsiflexion and eversion; L5 also supplies inversion (via the tibial nerve) and hip abduction (via the superior gluteal nerve). Weakness of those extra muscles moves the lesion proximal to the fibular nerve.', 'Length-dependent polyneuropathies affect the longest axons first, so symptoms start in both feet, rise to the knees and then reach the fingertips, with early loss of ankle reflexes. Patchy involvement of separate named nerves (multiple mononeuropathies) and early proximal or facial involvement suggest other processes.'],
 nmj: ['At the junction, each nerve impulse releases acetylcholine that binds receptors on the muscle. When transmission is marginal, repeated use releases slightly less each time and some fibres fail, so weakness grows with effort and recovers with rest. Eyelid and eye muscles are especially sensitive, so ptosis and double vision are common first signs.', 'Because nerves and the sensory system are normal, sensation and tendon reflexes are preserved in typical myasthenia, and pupils are spared. A useful bedside sign is ptosis that worsens with sustained upgaze and improves after rest.', 'In Lambert–Eaton syndrome, antibodies reduce calcium entry into the nerve terminal, so less acetylcholine is released. Reflexes are reduced at rest but may return after brief maximal effort, strength may briefly improve, and autonomic symptoms such as dry mouth are common.'],
 muscle: ['Myopathies usually weaken the large proximal muscles of the shoulders and hips first, giving trouble with stairs, rising from a chair and reaching overhead. Strength should be tested against resistance in each group, because tiredness alone is not weakness.', 'In a muscle disorder, sensation is normal and reflexes are kept until weakness is severe. Look at neck flexors, face, eyelids and swallowing too, because some myopathies involve them. Any sensory loss, fasciculation or upper motor neuron sign means another level is involved.', 'A raised creatine kinase and short, small motor units on needle examination support muscle as the level. Some myopathies are selective, such as finger flexor and quadriceps weakness, and distal or asymmetric patterns can mimic nerve disease.'],
 cerebellum: ['The cerebellum compares intended and actual movement and corrects errors. When it fails, movements overshoot or undershoot (dysmetria), alternating movements become irregular, and tremor appears near the target. Strength is normal, which separates ataxia from weakness.', 'The midline vermis controls trunk posture and gait; the hemispheres coordinate the limbs on their own side, because cerebellar pathways cross twice. Slurred, scanning speech and eye movement abnormalities such as nystagmus or jerky pursuit support a cerebellar cause.', 'Sensory ataxia comes from loss of position sense, from posterior columns, roots, ganglia or large nerve fibres. It gets much worse with the eyes closed (Romberg sign), while cerebellar ataxia changes little. Vestibular ataxia causes vertigo and imbalance with eye movement signs.'],
 vision: ['In front of the chiasm, each optic nerve carries only one eye, so a lesion there causes loss in that eye, reduced colour vision and a relative afferent pupillary defect. At the chiasm, nasal retinal fibres cross, so central chiasmal lesions remove both temporal fields.', 'Behind the chiasm, each optic tract and radiation carries the opposite half of the visual world from both eyes, giving homonymous defects. The further back the lesion, the more alike the defects in the two eyes (congruity). Occipital lesions often spare central vision.', 'Lower fibres of the optic radiation loop through the temporal lobe (Meyer loop) and carry the upper field; upper fibres pass through the parietal lobe and carry the lower field. So a temporal lesion causes an upper quadrant defect ("pie in the sky") and a parietal lesion a lower quadrant defect.'],
 sensory: ['The dorsal column–medial lemniscus pathway carries vibration, position sense and fine touch. Fibres enter the cord and ascend on the same side to the medulla, where they synapse, cross and continue to the thalamus and cortex. Below the medulla, damage causes loss on the same side.', 'The spinothalamic pathway carries pain and temperature. Fibres enter the cord, cross within a few segments and ascend on the opposite side to the thalamus. A lesion of one tract therefore causes loss on the opposite side, starting a level or two below the lesion.', 'Because the two systems cross at different levels, lesions can separate them. Central cord lesions cut crossing pain fibres in a band, sparing vibration; hemicord lesions split the modalities between the two sides; lateral medullary lesions split face and body.'],
 eyes: ['The pupils compare light input from both eyes. Swinging a light from one eye to the other reveals an afferent defect: the pupils dilate when the light reaches the weaker eye. Efferent problems change one pupil: a third nerve palsy gives a large, poorly reactive pupil; a Horner syndrome a small one, most obvious in dim light.', 'Double vision is worst when looking in the direction of action of the weak muscle. Horizontal diplopia points to the medial or lateral rectus; vertical diplopia to the vertical recti or obliques. Covering each eye in turn shows which image belongs to which eye: the outer image comes from the weak eye.', 'Nuclear and supranuclear lesions affect both eyes in a coordinated way. A sixth nerve lesion stops one eye abducting, a sixth nucleus lesion stops both eyes looking to that side, and an MLF lesion stops one eye adducting while convergence is preserved. Reflex eye movements that exceed voluntary ones point above the nuclei.'],
 leg: ['The lumbar plexus (L2–L4) forms the femoral and obturator nerves for the front and inside of the thigh. The sacral plexus (L4–S3) forms the gluteal nerves and the sciatic nerve, which divides above the knee into the tibial and common fibular nerves.', 'In foot drop, test inversion and hip abduction. Both share L5 but use the tibial and superior gluteal nerves, so their weakness points to the root. Sensory loss on the top of the foot and lateral leg with strong inversion points to the common fibular nerve, often at the fibular head.', 'A plexopathy affects several nerves in one leg, often with severe pain, and reduces sensory nerve responses. A combined femoral and obturator deficit suggests the lumbar plexus or L3–L4 roots; paraspinal muscle and sensory nerve studies separate the two.']
};
