'use strict';
/* NeuroLocalize 1.2 additions: diagram-linked recall cards and the Pattern Finder teaching heuristic.
   Sources reference ids already defined in the curriculum and case banks. */
window.NL_EXTRAS = {
 cards: [
  {id:'x01',topicId:'motor',front:'Which signs point to an upper rather than a lower motor neuron lesion?',back:'Increased tone, brisk reflexes and an extensor plantar response, with weakness in a pyramidal pattern and little early wasting.',sourceIds:['s-weakness','cs-reflexes']},
  {id:'x02',topicId:'motor',front:'Why can an acute central lesion resemble a lower motor neuron lesion?',back:'Soon after an acute lesion, tone and reflexes can be reduced before spasticity and brisk reflexes develop.',sourceIds:['s-weakness','s-cord']},
  {id:'x03',topicId:'cranial',front:'Why is the forehead often spared in a central facial palsy?',back:'Upper-face motor neurons receive input from both hemispheres, so a one-sided lesion above the nucleus mainly weakens the opposite lower face.',sourceIds:['cs-facial','s-cranial']},
  {id:'x04',topicId:'vision',front:'Which field defect follows a central chiasmal lesion?',back:'A bitemporal hemianopia, from interrupted crossing nasal retinal fibers.',sourceIds:['s-vision','cs-fields']},
  {id:'x05',topicId:'vision',front:'A right temporal lesion involving Meyer loop causes which field defect?',back:'A left (contralateral) superior homonymous quadrantanopia.',sourceIds:['s-vision','cx-homonymous']},
  {id:'x06',topicId:'brainstem',front:"Name the four medial structures in the brainstem 'rule of 4'.",back:'Motor pathway, medial lemniscus, medial longitudinal fasciculus and the motor nuclei of III, IV, VI or XII.',sourceIds:['s-brainstem','cs-medial-medulla']},
  {id:'x07',topicId:'brainstem',front:"Name the four lateral structures in the brainstem 'rule of 4'.",back:'Spinocerebellar connections, spinothalamic tract, sensory nucleus of V and the descending sympathetic pathway.',sourceIds:['s-brainstem','cs-lateral-medulla']},
  {id:'x08',topicId:'cranial',front:'How does an abducens nucleus lesion differ from an abducens nerve lesion?',back:'The nucleus lesion causes a same-side horizontal gaze palsy of both eyes; the nerve lesion weakens abduction of one eye only.',sourceIds:['rw-abducens-nucleus','cs-sixth']},
  {id:'x09',topicId:'cranial',front:'In a left internuclear ophthalmoplegia, which eye fails to adduct?',back:'The left eye, on gaze to the right, often with nystagmus of the abducting right eye.',sourceIds:['cx-ino','cs-ino']},
  {id:'x10',topicId:'cord',front:'Which modalities are spared in an anterior cord syndrome?',back:'Vibration and joint position sense, carried in the dorsal columns.',sourceIds:['cs-cord-syndromes','s-cord']},
  {id:'x11',topicId:'sensory',front:'Where do the dorsal column and spinothalamic pathways cross?',back:'Dorsal column fibers cross in the medulla; spinothalamic fibers cross within a few segments of their entry into the cord.',sourceIds:['s-dorsal','s-somatosensory']},
  {id:'x12',topicId:'roots',front:'Weak great-toe extension with a normal ankle reflex points most to which root?',back:'L5. It has no reliable routine reflex, whereas the ankle reflex depends mainly on S1.',sourceIds:['s-roots','cs-reflexes']},
  {id:'x13',topicId:'roots',front:'Which root does the triceps reflex mainly test?',back:'C7.',sourceIds:['cs-reflexes','s-roots']},
  {id:'x14',topicId:'plexus',front:'Which cords combine to form the median nerve?',back:'The lateral and medial cords.',sourceIds:['s-plexus','px-brachial']},
  {id:'x15',topicId:'plexus',front:'Which terminal nerves arise from the posterior cord?',back:'The axillary and radial nerves.',sourceIds:['s-plexus','px-brachial']},
  {id:'x16',topicId:'nmj',front:'Which reflex behavior favors Lambert–Eaton over myasthenia gravis?',back:'Reduced reflexes that can increase after a brief maximal contraction.',sourceIds:['s-lems','px-nmj-edx']},
  {id:'x17',topicId:'cortex',front:'Which classic aphasias impair repetition?',back:'Broca, Wernicke, conduction and global aphasia: the types involving the perisylvian language loop.',sourceIds:['cx-language','cx-conduction']},
  {id:'x18',topicId:'cortex',front:'Fluent speech, good comprehension, poor repetition: which aphasia?',back:'Conduction aphasia.',sourceIds:['cx-conduction','cs-aphasia']},
  {id:'x19',topicId:'cortex',front:'Which arterial territory classically gives contralateral leg-predominant weakness?',back:'The anterior cerebral artery, which supplies the medial frontal and parietal cortex where the leg is represented.',sourceIds:['cs-cerebral','s-cortex']},
  {id:'x20',topicId:'brainstem',front:'Where do second-order sympathetic fibers to the eye travel?',back:'From the upper thoracic cord, near the lung apex, up to the superior cervical ganglion.',sourceIds:['cx-horner']},
  {id:'x21',topicId:'nerves',front:'What does a stocking-and-glove sensory pattern suggest?',back:'A length-dependent polyneuropathy, which affects the longest nerves first.',sourceIds:['s-poly','s-numbness']},
  {id:'y01',topicId:'eyes',front:'What does a relative afferent pupillary defect indicate?',back:'Reduced light input from one eye, usually from optic nerve disease or extensive retinal disease on that side.',sourceIds:['cx-tract-pupil','cs-optic']},
  {id:'y02',topicId:'eyes',front:'Which extraocular muscles are not supplied by the third nerve?',back:'The lateral rectus (VI) and the superior oblique (IV).',sourceIds:['rw-eye-movement','cs-third']},
  {id:'y03',topicId:'eyes',front:'Which muscle depresses the eye most effectively in adduction?',back:'The superior oblique, supplied by the fourth nerve.',sourceIds:['cx-fourth','rw-eye-movement']},
  {id:'y04',topicId:'eyes',front:'Which cranial nerve lies within the cavernous sinus beside the carotid artery?',back:'The abducens nerve (VI); III, IV, V1 and V2 run in the lateral wall.',sourceIds:['cx-cavernous','cs-sixth']},
  {id:'y05',topicId:'eyes',front:'Why does light in one eye constrict both pupils?',back:'Pretectal neurons project to both Edinger–Westphal nuclei, which drive both pupil constrictors.',sourceIds:['cx-tract-pupil']},
  {id:'y06',topicId:'eyes',front:'A large, poorly reactive pupil with ptosis and an eye that rests down and out suggests what?',back:'A third nerve palsy.',sourceIds:['cs-third']},
  {id:'y07',topicId:'leg',front:'In foot drop, what does weak foot inversion suggest?',back:'An L5 root lesion rather than a common fibular neuropathy, because inversion uses L5 through the tibial nerve.',sourceIds:['cs-fibular','px-deep-fibular']},
  {id:'y08',topicId:'leg',front:'Which nerve adducts the hip?',back:'The obturator nerve (L2–L4).',sourceIds:['px-obturator']},
  {id:'y09',topicId:'leg',front:'Which nerve extends the knee and carries the knee reflex?',back:'The femoral nerve (L2–L4); its saphenous branch supplies the medial leg.',sourceIds:['px-femoral']},
  {id:'y10',topicId:'roots',front:'Which dermatome includes the umbilicus?',back:'T10.',sourceIds:['s-dermatomes']},
  {id:'y11',topicId:'roots',front:'Which dermatome includes the nipple line?',back:'T4.',sourceIds:['s-dermatomes']},
  {id:'y12',topicId:'roots',front:'Which root supplies sensation to the middle finger?',back:'C7.',sourceIds:['s-dermatomes','s-roots']},
  {id:'y13',topicId:'nerves',front:'Sensory loss that splits the ring finger suggests what?',back:'A nerve lesion (ulnar or median) rather than a C8 root lesion, which tends to involve the whole finger.',sourceIds:['cs-ulnar','cs-carpal']},
  {id:'y14',topicId:'cord',front:'How does pain usually differ between conus and cauda equina lesions?',back:'Radicular pain is typically prominent in cauda equina lesions and less prominent in conus lesions.',sourceIds:['cs-cauda']},
  {id:'y15',topicId:'motor',front:'Reflexes are brisk rather than reduced. Where is the lesion relative to the reflex arc?',back:'Above it, in the descending upper motor neuron pathways; damage within the arc reduces reflexes.',sourceIds:['cs-reflexes','s-weakness']},
  {id:'y16',topicId:'approach',front:'What does a sudden onset over seconds to minutes tend to suggest?',back:'A vascular event, seizure or trauma, though localization remains the first step.',sourceIds:['s-approach']},
  {id:'y17',topicId:'approach',front:'What does slow progression over months to years tend to suggest?',back:'A degenerative, neoplastic or genetic process.',sourceIds:['s-approach']}
 ],
 topics: [
  {id:'eyes',after:'cranial',drill:'eyes',title:'Pupils and eye movements',kicker:'EYES',description:'Use pupils, gaze and double vision to place a lesion.',icon:'eye',level:'Intermediate',minutes:6,summary:'Separate an afferent from an efferent pupil problem, then ask whether a movement deficit fits a nerve, a nucleus or a gaze pathway.',sections:[
   {heading:'1 · Pupils: afferent or efferent?',text:'Light in either eye normally constricts both pupils. An afferent defect, such as optic nerve disease, reduces the response to light in the affected eye and shows up with the swinging light test. An efferent defect affects one pupil whichever eye is lit.',bullets:['Relative afferent pupillary defect: optic nerve or extensive retinal disease on that side','Large, poorly reactive pupil with ptosis or limited eye movement: third nerve','Small pupil with mild ptosis: the sympathetic (Horner) pathway']},
   {heading:'2 · Which muscle, which nerve?',text:'The lateral rectus is supplied by VI and the superior oblique by IV; III supplies the other extraocular muscles, the eyelid elevator and the pupil constrictor. Map double vision to the direction in which the images separate most.',bullets:['Horizontal diplopia worse looking to one side: a horizontal muscle acting in that direction','Vertical diplopia worse looking down and away from the affected eye: superior oblique (IV)']},
   {heading:'3 · Nerve, nucleus or gaze pathway?',text:'A single nerve palsy limits one eye. Nuclear and supranuclear lesions disturb coordinated movement: an abducens nucleus lesion causes a horizontal gaze palsy and an MLF lesion causes internuclear ophthalmoplegia. Several cranial nerves together on one side suggest the cavernous sinus or orbital apex.'}],
   pearls:['Ask which eye, which direction and whether the pupil is involved.','A gaze palsy moving both eyes points above the cranial nerve.'],
   pitfall:'Fatigable, variable weakness of eye movement that fits no single nerve should raise a neuromuscular junction disorder; the pupils are spared there.',
   sourceIds:['cx-tract-pupil','cs-third','cs-sixth','cx-fourth','cx-cavernous','rw-eye-movement']},
  {id:'leg',after:'plexus',drill:'nerves',title:'Nerves of the leg',kicker:'LUMBOSACRAL',description:'Separate a root, plexus and single nerve in the leg.',icon:'network',level:'Intermediate',minutes:6,summary:'Use muscles that share a root but not a nerve to tell an L5 radiculopathy from a fibular neuropathy, and learn the femoral and obturator territories.',sections:[
   {heading:'1 · Map the main nerves',text:'The femoral nerve (L2–L4) extends the knee and carries the knee reflex; its saphenous branch supplies the medial leg. The obturator nerve (L2–L4) adducts the hip. The sciatic nerve divides into the tibial nerve, for plantar flexion and inversion, and the common fibular nerve, for dorsiflexion and eversion.'},
   {heading:'2 · Foot drop: root or nerve?',text:'Both an L5 radiculopathy and a common fibular neuropathy weaken ankle dorsiflexion. Muscles that share L5 but use other nerves separate them.',bullets:['Weak foot inversion (tibial nerve) favors L5','Weak hip abduction (superior gluteal nerve) favors L5','Sensory change limited to the lateral leg and dorsum of the foot fits the fibular nerve']},
   {heading:'3 · When the plexus is the answer',text:'A lumbosacral plexopathy affects muscles across several nerves and roots in one leg, often with pain. Thigh weakness involving both femoral and obturator territories without features of a single root should prompt plexus thinking.'}],
   pearls:['Test inversion and hip abduction in every foot drop.','Weak hip adduction alongside weak knee extension points beyond the femoral nerve, to the L3–L4 roots or the plexus.'],
   pitfall:'A sciatic nerve lesion can mimic a fibular neuropathy because the fibular fibers are often affected more; look carefully at tibial-supplied muscles.',
   sourceIds:['px-lumbosacral','px-femoral','px-obturator','cs-fibular','px-deep-fibular','cs-roots']}
 ],
 drills: [
  {id:'roots',title:'Root signatures',description:'Reflexes, movements and dermatome points.',diagram:'root-signatures',prompt:'Which root best matches this?',items:[
   ['Biceps reflex','C5–C6'],['Brachioradialis reflex','C6'],['Triceps reflex','C7'],['Knee reflex','L3–L4'],['Ankle reflex','S1'],
   ['Shoulder abduction','C5'],['Wrist extension','C6'],['Finger flexion and small hand muscles','C8'],['Great-toe extension','L5'],
   ['Sensation over the thumb','C6'],['Sensation over the middle finger','C7'],['Sensation over the little finger','C8'],
   ['Sensation at the umbilicus','T10'],['Sensation at the nipple line','T4'],['Sensation at the medial ankle','L4'],['Sensation at the outer heel','S1']]},
  {id:'fields',title:'Visual field defects',description:'Match the field loss to the lesion.',diagram:'field-defects',prompt:'Where is the lesion most likely?',items:[
   ['Loss of vision in one eye only','Optic nerve'],['Central scotoma in one eye with a relative afferent pupillary defect','Optic nerve'],
   ['Bitemporal hemianopia','Optic chiasm'],['Incongruous contralateral homonymous hemianopia','Optic tract'],
   ['Contralateral homonymous superior quadrantanopia','Temporal lobe (Meyer loop)'],['Contralateral homonymous inferior quadrantanopia','Parietal optic radiation'],
   ['Congruous contralateral hemianopia with macular sparing','Occipital cortex']]},
  {id:'aphasia',title:'Aphasia types',description:'Fluency, comprehension, repetition.',diagram:'aphasia-tree',prompt:'Which aphasia fits best?',items:[
   ['Nonfluent; comprehends; cannot repeat','Broca aphasia'],['Nonfluent; comprehends; repeats well','Transcortical motor aphasia'],
   ['Nonfluent; poor comprehension; cannot repeat','Global aphasia'],['Nonfluent; poor comprehension; repeats well','Mixed transcortical aphasia'],
   ['Fluent; comprehends; cannot repeat','Conduction aphasia'],['Fluent; comprehends; repeats; word-finding pauses','Anomic aphasia'],
   ['Fluent; poor comprehension; cannot repeat','Wernicke aphasia'],['Fluent; poor comprehension; repeats well','Transcortical sensory aphasia']]},
  {id:'eyes',title:'Eye muscles',description:'Actions, best test positions and nerves.',diagram:'eye-muscles',prompt:'Which muscle is this?',items:[
   ['Abducts the eye','Lateral rectus (VI)'],['Adducts the eye','Medial rectus (III)'],['Depresses the eye best in adduction','Superior oblique (IV)'],
   ['Elevates the eye best in adduction','Inferior oblique (III)'],['Elevates the eye best in abduction','Superior rectus (III)'],['Depresses the eye best in abduction','Inferior rectus (III)']]},
  {id:'brainstem',title:'Brainstem syndromes',description:'Level and medial or lateral.',diagram:'brainstem-rule',prompt:'Where is the lesion most likely?',items:[
   ['Same-side third nerve palsy with opposite arm and leg weakness','Medial midbrain'],
   ['Same-side abducens palsy with opposite hemiparesis','Medial pons'],
   ['Same-side tongue weakness, opposite hemiparesis and opposite vibration loss','Medial medulla'],
   ['Same-side facial pain loss and Horner syndrome, opposite body pain loss, hoarseness','Lateral medulla'],
   ['Same-side facial weakness, hearing loss and limb ataxia with opposite body pain loss','Lateral pons']]},
  {id:'nerves',title:'Arm and leg nerves',description:'Name the nerve from the deficit.',diagram:'lumbosacral',prompt:'Which nerve is most likely affected?',items:[
   ['Wrist drop with numbness over the back of the first web space','Radial nerve'],
   ['Weak thumb abduction with numb index fingertip','Median nerve'],
   ['Weak finger spreading, numb little finger and split ring finger','Ulnar nerve'],
   ['Weak deltoid with a numb patch over the lateral shoulder','Axillary nerve'],
   ['Weak elbow flexion with numb lateral forearm','Musculocutaneous nerve'],
   ['Foot drop and weak eversion with inversion spared','Common fibular nerve'],
   ['Weak knee extension and absent knee reflex with hip adduction spared','Femoral nerve'],
   ['Weak hip adduction with medial thigh numbness','Obturator nerve'],
   ['Weak plantar flexion with numbness of the sole','Tibial nerve']]}
 ],
 finder: {
  levels: [
   {id:'cortex',title:'Cerebral cortex',topic:'cortex',diagram:'cortex',test:'Look for language, neglect, field or cortical sensory signs that subcortical lesions rarely produce alone.'},
   {id:'deep',title:'Deep hemisphere (capsule, thalamus)',topic:'subcortex',diagram:'compact',test:'A dense face–arm–leg pattern without cortical signs favors compact deep pathways.'},
   {id:'brainstem',title:'Brainstem',topic:'brainstem',diagram:'brainstem-rule',test:'A cranial nerve or gaze sign sets the level; look for crossed sensory or limb findings.'},
   {id:'cord',title:'Spinal cord',topic:'cord',diagram:'cord-syndromes',test:'Search for a sensory level, bilateral long-tract signs and sphincter change; the face is spared.'},
   {id:'root',title:'Nerve root',topic:'roots',diagram:'root-signatures',test:'Compare muscles that share a root but use different nerves, and check the matching reflex.'},
   {id:'plexus',title:'Plexus',topic:'plexus',diagram:'brachial-plexus',test:'Deficits span several nerves and more than one root within one limb.'},
   {id:'nerve',title:'Single peripheral nerve',topic:'nerves',diagram:'peripheral',test:'Weakness and sensory loss map onto one named nerve and its branches.'},
   {id:'poly',title:'Polyneuropathy',topic:'nerves',diagram:'body-patterns',test:'Distal, symmetric, length-dependent findings with reduced ankle reflexes.'},
   {id:'nmj',title:'Neuromuscular junction',topic:'nmj',diagram:'nmj-compare',test:'Fatigable weakness with eye or bulbar involvement and normal sensation.'},
   {id:'muscle',title:'Muscle',topic:'muscle',diagram:'motor-unit',test:'Symmetric proximal weakness, normal sensation, reflexes preserved until late.'},
   {id:'cerebellum',title:'Cerebellum and its connections',topic:'cerebellum',diagram:'coordination',test:'Ataxia with preserved strength and position sense; check eye movements.'}
  ],
  groups: ['Motor','Sensory','Other clues'],
  findings: [
   {id:'umn',group:'Motor',label:'Brisk reflexes, spasticity or an extensor plantar',w:{cortex:2,deep:2,brainstem:2,cord:2,root:-3,plexus:-3,nerve:-3,poly:-3,nmj:-3,muscle:-3,cerebellum:-1}},
   {id:'lmn',group:'Motor',label:'Reduced reflexes, wasting or fasciculation in weak muscles',w:{root:2,plexus:2,nerve:2,poly:2,cord:1,cortex:-2,deep:-2,brainstem:-1,cerebellum:-1}},
   {id:'hemi',group:'Motor',label:'Face, arm and leg weak on the same side',w:{cortex:2,deep:3,brainstem:1,cord:-3,root:-3,plexus:-3,nerve:-3,poly:-3,nmj:-2,muscle:-3,cerebellum:-2}},
   {id:'para',group:'Motor',label:'Both legs weak, arms spared',w:{cord:3,root:1,deep:-1,brainstem:-1,nerve:-3,plexus:-2,nmj:-1,cerebellum:-2}},
   {id:'proximal',group:'Motor',label:'Symmetric proximal weakness (shoulders, hips)',w:{muscle:3,nmj:2,poly:-1,nerve:-3,root:-2,plexus:-2,cortex:-3,deep:-3,brainstem:-2,cerebellum:-3}},
   {id:'fatigue',group:'Motor',label:'Fatigable weakness, fluctuating ptosis or double vision',w:{nmj:4,brainstem:1,cortex:-2,deep:-2,cord:-2,root:-2,plexus:-2,nerve:-1,poly:-1,cerebellum:-2}},
   {id:'limb',group:'Motor',label:'Weakness across several nerves in one limb',w:{plexus:3,root:1,nerve:-1,brainstem:-1,poly:-2,nmj:-2,muscle:-2,cerebellum:-2}},
   {id:'single',group:'Motor',label:'Weakness and numbness in one named nerve territory',w:{nerve:4,root:1,poly:-1,cortex:-2,deep:-2,brainstem:-2,cord:-2,nmj:-3,muscle:-3,cerebellum:-3}},
   {id:'cortical',group:'Sensory',label:'Aphasia, neglect or impaired stereognosis with intact primary sensation',w:{cortex:4,deep:1,brainstem:-2,cord:-3,root:-3,plexus:-3,nerve:-3,poly:-3,nmj:-3,muscle:-3,cerebellum:-3}},
   {id:'field',group:'Sensory',label:'Homonymous visual field defect',w:{cortex:2,deep:2,brainstem:-2,cord:-3,root:-3,plexus:-3,nerve:-3,poly:-3,nmj:-3,muscle:-3,cerebellum:-3}},
   {id:'crossed',group:'Sensory',label:'Face affected on one side, body on the other',w:{brainstem:4,cortex:-3,deep:-3,cord:-3,root:-3,plexus:-3,nerve:-3,poly:-3,nmj:-3,muscle:-3,cerebellum:-3}},
   {id:'level',group:'Sensory',label:'A sensory level on the trunk',w:{cord:4,root:-1,poly:-2,cortex:-3,deep:-3,brainstem:-3,plexus:-3,nerve:-3,nmj:-3,muscle:-3,cerebellum:-3}},
   {id:'dissociated',group:'Sensory',label:'Pain loss on one side, vibration loss on the other',w:{cord:3,brainstem:2,cortex:-3,deep:-3,root:-3,plexus:-3,nerve:-3,poly:-3,nmj:-3,muscle:-3,cerebellum:-3}},
   {id:'dermatomal',group:'Sensory',label:'Radiating limb pain or a dermatomal strip of numbness',w:{root:4,plexus:1,nerve:1,cortex:-2,deep:-2,brainstem:-2,poly:-2,nmj:-2,muscle:-2,cerebellum:-2}},
   {id:'stocking',group:'Sensory',label:'Distal symmetric stocking-and-glove sensory loss',w:{poly:4,root:-1,cortex:-2,deep:-2,brainstem:-2,plexus:-2,nerve:-2,nmj:-2,muscle:-2,cerebellum:-2}},
   {id:'nosensory',group:'Sensory',label:'Sensation entirely normal',w:{muscle:2,nmj:2,cerebellum:1,brainstem:-1,cord:-1,root:-1,plexus:-2,nerve:-2,poly:-3}},
   {id:'cranial',group:'Other clues',label:'Cranial nerve or gaze palsy with opposite-side limb signs',w:{brainstem:4,cortex:-3,deep:-3,cord:-3,root:-3,plexus:-3,nerve:-3,poly:-3,nmj:-3,muscle:-3,cerebellum:-2}},
   {id:'ataxia',group:'Other clues',label:'Same-side limb ataxia with normal strength and position sense',w:{cerebellum:4,brainstem:2,cortex:-2,cord:-2,root:-2,plexus:-2,nerve:-2,poly:-2,nmj:-2,muscle:-2}},
   {id:'sphincter',group:'Other clues',label:'Early bladder or bowel change with leg signs',w:{cord:3,root:1,deep:-2,brainstem:-2,plexus:-2,nerve:-2,poly:-2,nmj:-2,muscle:-2,cerebellum:-2}},
   {id:'bulbar',group:'Other clues',label:'Weak swallowing or slurred, weak articulation',w:{brainstem:2,nmj:2,muscle:1,cord:-2,root:-3,plexus:-3,nerve:-2,poly:-1,cerebellum:-1}}
  ]
 }
};
