'use strict';
/* NeuroLocalize 1.2 additions: diagram-linked recall cards and the Pattern Finder teaching heuristic.
   Sources reference ids already defined in the curriculum and case banks. */
window.NL_EXTRAS = {
 cards: [
  {id:'x01',topicId:'motor',front:'Which signs point to an upper rather than a lower motor neuron lesion?',back:'Increased tone, brisk reflexes and an extensor plantar response, with weakness in a pyramidal pattern and little early wasting.',sourceIds:['s-weakness','cs-reflexes']},
  {id:'x02',topicId:'motor',front:'Why can an acute central lesion resemble a lower motor neuron lesion?',back:'Soon after an acute lesion, tone and reflexes can be reduced before spasticity and brisk reflexes develop.',sourceIds:['s-weakness','s-cord']},
  {id:'x03',topicId:'cranial',front:'Why is the forehead often spared in a central facial palsy?',back:'Upper-face motor neurons receive input from both hemispheres, so a one-sided lesion above the nucleus mainly weakens the opposite lower face.',sourceIds:['cs-facial','s-cranial']},
  {id:'x04',topicId:'vision',front:'Which field defect follows a central chiasmal lesion?',back:'A bitemporal hemianopia, from interrupted crossing nasal retinal fibers.',sourceIds:['s-vision','cs-fields']},
  {id:'x05',topicId:'vision',front:'A right temporal lesion involving Meyer loop causes which field defect?',back:'A left (contralateral) superior homonymous quadrantanopia.',sourceIds:['s-vision','cx-homonymous']},
  {id:'x06',topicId:'brainstem',front:"Name the four medial structures in the brainstem 'rule of 4'.",back:'Motor pathway, medial lemniscus, medial longitudinal fasciculus and the motor nuclei of III, IV, VI or XII.',sourceIds:['s-brainstem','cs-medial-medulla']},
  {id:'x07',topicId:'brainstem',front:"Name the four lateral structures in the brainstem 'rule of 4'.",back:'Spinocerebellar connections, spinothalamic tract, sensory nucleus of V and the descending sympathetic pathway.',sourceIds:['s-brainstem','cs-lateral-medulla']},
  {id:'x08',topicId:'cranial',front:'How does an abducens nucleus lesion differ from an abducens nerve lesion?',back:'The nucleus lesion causes a same-side horizontal gaze palsy of both eyes; the nerve lesion weakens abduction of one eye only.',sourceIds:['rw-abducens-nucleus','cs-sixth']},
  {id:'x09',topicId:'cranial',front:'In a left internuclear ophthalmoplegia, which eye fails to adduct?',back:'The left eye, on gaze to the right, often with nystagmus of the abducting right eye.',sourceIds:['cx-ino','cs-ino']},
  {id:'x10',topicId:'cord',front:'Which modalities are spared in an anterior cord syndrome?',back:'Vibration and joint position sense, carried in the dorsal columns.',sourceIds:['cs-cord-syndromes','s-cord']},
  {id:'x11',topicId:'sensory',front:'Where do the dorsal column and spinothalamic pathways cross?',back:'Dorsal column fibers cross in the medulla; spinothalamic fibers cross within a few segments of their entry into the cord.',sourceIds:['s-dorsal','s-somatosensory']},
  {id:'x12',topicId:'roots',front:'Weak great-toe extension with a normal ankle reflex points most to which root?',back:'L5. It has no reliable routine reflex, whereas the ankle reflex depends mainly on S1.',sourceIds:['s-roots','cs-reflexes']},
  {id:'x13',topicId:'roots',front:'Which root does the triceps reflex mainly test?',back:'C7.',sourceIds:['cs-reflexes','s-roots']},
  {id:'x14',topicId:'plexus',front:'Which cords combine to form the median nerve?',back:'The lateral and medial cords.',sourceIds:['s-plexus','px-brachial']},
  {id:'x15',topicId:'plexus',front:'Which terminal nerves arise from the posterior cord?',back:'The axillary and radial nerves.',sourceIds:['s-plexus','px-brachial']},
  {id:'x16',topicId:'nmj',front:'Which reflex behavior favors Lambert–Eaton over myasthenia gravis?',back:'Reduced reflexes that can increase after a brief maximal contraction.',sourceIds:['s-lems','px-nmj-edx']},
  {id:'x17',topicId:'cortex',front:'Which classic aphasias impair repetition?',back:'Broca, Wernicke, conduction and global aphasia: the types involving the perisylvian language loop.',sourceIds:['cx-language','cx-conduction']},
  {id:'x18',topicId:'cortex',front:'Fluent speech, good comprehension, poor repetition: which aphasia?',back:'Conduction aphasia.',sourceIds:['cx-conduction','cs-aphasia']},
  {id:'x19',topicId:'cortex',front:'Which arterial territory classically gives contralateral leg-predominant weakness?',back:'The anterior cerebral artery, which supplies the medial frontal and parietal cortex where the leg is represented.',sourceIds:['cs-cerebral','s-cortex']},
  {id:'x20',topicId:'brainstem',front:'Where do second-order sympathetic fibers to the eye travel?',back:'From the upper thoracic cord, near the lung apex, up to the superior cervical ganglion.',sourceIds:['cx-horner']},
  {id:'x21',topicId:'nerves',front:'What does a stocking-and-glove sensory pattern suggest?',back:'A length-dependent polyneuropathy, which affects the longest nerves first.',sourceIds:['s-poly','s-numbness']},
  {id:'y01',topicId:'eyes',front:'What does a relative afferent pupillary defect indicate?',back:'Reduced light input from one eye, usually from optic nerve disease or extensive retinal disease on that side.',sourceIds:['cx-tract-pupil','cs-optic']},
  {id:'y02',topicId:'eyes',front:'Which extraocular muscles are not supplied by the third nerve?',back:'The lateral rectus (VI) and the superior oblique (IV).',sourceIds:['rw-eye-movement','cs-third']},
  {id:'y03',topicId:'eyes',front:'Which muscle depresses the eye most effectively in adduction?',back:'The superior oblique, supplied by the fourth nerve.',sourceIds:['cx-fourth','rw-eye-movement']},
  {id:'y04',topicId:'eyes',front:'Which cranial nerve lies within the cavernous sinus beside the carotid artery?',back:'The abducens nerve (VI); III, IV, V1 and V2 run in the lateral wall.',sourceIds:['cx-cavernous','cs-sixth']},
  {id:'y05',topicId:'eyes',front:'Why does light in one eye constrict both pupils?',back:'Pretectal neurons project to both Edinger–Westphal nuclei, which drive both pupil constrictors.',sourceIds:['cx-tract-pupil']},
  {id:'y06',topicId:'eyes',front:'A large, poorly reactive pupil with ptosis and an eye that rests down and out suggests what?',back:'A third nerve palsy.',sourceIds:['cs-third']},
  {id:'y07',topicId:'leg',front:'In foot drop, what does weak foot inversion suggest?',back:'An L5 root lesion rather than a common fibular neuropathy, because inversion uses L5 through the tibial nerve.',sourceIds:['cs-fibular','px-deep-fibular']},
  {id:'y08',topicId:'leg',front:'Which nerve adducts the hip?',back:'The obturator nerve (L2–L4).',sourceIds:['px-obturator']},
  {id:'y09',topicId:'leg',front:'Which nerve extends the knee and carries the knee reflex?',back:'The femoral nerve (L2–L4); its saphenous branch supplies the medial leg.',sourceIds:['px-femoral']},
  {id:'y10',topicId:'roots',front:'Which dermatome includes the umbilicus?',back:'T10.',sourceIds:['s-dermatomes']},
  {id:'y11',topicId:'roots',front:'Which dermatome includes the nipple line?',back:'T4.',sourceIds:['s-dermatomes']},
  {id:'y12',topicId:'roots',front:'Which root supplies sensation to the middle finger?',back:'C7.',sourceIds:['s-dermatomes','s-roots']},
  {id:'y13',topicId:'nerves',front:'Sensory loss that splits the ring finger suggests what?',back:'A nerve lesion (ulnar or median) rather than a C8 root lesion, which tends to involve the whole finger.',sourceIds:['cs-ulnar','cs-carpal']},
  {id:'y14',topicId:'cord',front:'How does pain usually differ between conus and cauda equina lesions?',back:'Radicular pain is typically prominent in cauda equina lesions and less prominent in conus lesions.',sourceIds:['cs-cauda']},
  {id:'y15',topicId:'motor',front:'Reflexes are brisk rather than reduced. Where is the lesion relative to the reflex arc?',back:'Above it, in the descending upper motor neuron pathways; damage within the arc reduces reflexes.',sourceIds:['cs-reflexes','s-weakness']},
  {id:'y16',topicId:'approach',front:'What does a sudden onset over seconds to minutes tend to suggest?',back:'A vascular event, seizure or trauma, though localization remains the first step.',sourceIds:['s-approach']},
  {id:'y17',topicId:'approach',front:'What does slow progression over months to years tend to suggest?',back:'A degenerative, neoplastic or genetic process.',sourceIds:['s-approach']}
 ],
 topics: [
  {id:'eyes',after:'cranial',drill:'eyes',title:'Pupils and eye movements',kicker:'EYES',description:'Use pupils, gaze and double vision to place a lesion.',icon:'eye',level:'Intermediate',minutes:6,summary:'Separate an afferent from an efferent pupil problem, then ask whether a movement deficit fits a nerve, a nucleus or a gaze pathway.',sections:[
   {heading:'1 · Pupils: afferent or efferent?',text:'Light in either eye normally constricts both pupils. An afferent defect, such as optic nerve disease, reduces the response to light in the affected eye and shows up with the swinging light test. An efferent defect affects one pupil whichever eye is lit.',bullets:['Relative afferent pupillary defect: optic nerve or extensive retinal disease on that side','Large, poorly reactive pupil with ptosis or limited eye movement: third nerve','Small pupil with mild ptosis: the sympathetic (Horner) pathway']},
   {heading:'2 · Which muscle, which nerve?',text:'The lateral rectus is supplied by VI and the superior oblique by IV; III supplies the other extraocular muscles, the eyelid elevator and the pupil constrictor. Map double vision to the direction in which the images separate most.',bullets:['Horizontal diplopia worse looking to one side: a horizontal muscle acting in that direction','Vertical diplopia worse looking down and away from the affected eye: superior oblique (IV)']},
   {heading:'3 · Nerve, nucleus or gaze pathway?',text:'A single nerve palsy limits one eye. Nuclear and supranuclear lesions disturb coordinated movement: an abducens nucleus lesion causes a horizontal gaze palsy and an MLF lesion causes internuclear ophthalmoplegia. Several cranial nerves together on one side suggest the cavernous sinus or orbital apex.'}],
   pearls:['Ask which eye, which direction and whether the pupil is involved.','A gaze palsy moving both eyes points above the cranial nerve.'],
   pitfall:'Fatigable, variable weakness of eye movement that fits no single nerve should raise a neuromuscular junction disorder; the pupils are spared there.',
   sourceIds:['cx-tract-pupil','cs-third','cs-sixth','cx-fourth','cx-cavernous','rw-eye-movement']},
  {id:'leg',after:'plexus',drill:'nerves',title:'Nerves of the leg',kicker:'LUMBOSACRAL',description:'Separate a root, plexus and single nerve in the leg.',icon:'network',level:'Intermediate',minutes:6,summary:'Use muscles that share a root but not a nerve to tell an L5 radiculopathy from a fibular neuropathy, and learn the femoral and obturator territories.',sections:[
   {heading:'1 · Map the main nerves',text:'The femoral nerve (L2–L4) extends the knee and carries the knee reflex; its saphenous branch supplies the medial leg. The obturator nerve (L2–L4) adducts the hip. The sciatic nerve divides into the tibial nerve, for plantar flexion and inversion, and the common fibular nerve, for dorsiflexion and eversion.'},
   {heading:'2 · Foot drop: root or nerve?',text:'Both an L5 radiculopathy and a common fibular neuropathy weaken ankle dorsiflexion. Muscles that share L5 but use other nerves separate them.',bullets:['Weak foot inversion (tibial nerve) favors L5','Weak hip abduction (superior gluteal nerve) favors L5','Sensory change limited to the lateral leg and dorsum of the foot fits the fibular nerve']},
   {heading:'3 · When the plexus is the answer',text:'A lumbosacral plexopathy affects muscles across several nerves and roots in one leg, often with pain. Thigh weakness involving both femoral and obturator territories without features of a single root should prompt plexus thinking.'}],
   pearls:['Test inversion and hip abduction in every foot drop.','Weak hip adduction alongside weak knee extension points beyond the femoral nerve, to the L3–L4 roots or the plexus.'],
   pitfall:'A sciatic nerve lesion can mimic a fibular neuropathy because the fibular fibers are often affected more; look carefully at tibial-supplied muscles.',
   sourceIds:['px-lumbosacral','px-femoral','px-obturator','cs-fibular','px-deep-fibular','cs-roots']}
 ],
 drills: [
  {id:'roots',title:'Root signatures',description:'Short neck and back pain cases: name the nerve root.',diagram:'root-signatures',prompt:'Which nerve root is most likely affected?',items:[
   ['A 45-year-old has neck pain shooting to the shoulder. The biceps jerk is reduced and the arm is weak lifting out to the side.','C5–C6','The biceps reflex and shoulder abduction both run through C5–C6.'],
   ['A 50-year-old gardener has neck pain into the thumb. The forearm (brachioradialis) reflex is lost and wrist extension is weak.','C6','Thumb numbness, wrist extension and the brachioradialis reflex are the C6 triad.'],
   ['A 52-year-old has pain down the back of the arm into the middle finger. The triceps jerk is gone and elbow straightening is weak.','C7','Triceps reflex, elbow extension and the middle finger all belong to C7.'],
   ['A 60-year-old has numbness of the little finger and the inner forearm. Gripping and fine finger movements are weak.','C8','C8 supplies the little finger, the inner forearm and the long finger flexors and hand muscles.'],
   ['A 40-year-old has pain down the front of the thigh to the inner shin. The knee jerk is reduced and climbing stairs is hard.','L3–L4','The knee reflex and knee extension come from L3–L4, and L4 reaches the inner shin and ankle.'],
   ['A 38-year-old lifted a heavy box and now has pain down the side of the leg to the top of the foot. He cannot lift his big toe; the ankle jerk is normal.','L5','Big-toe extension and the top of the foot are L5; L5 has no reliable reflex, so the ankle jerk is spared.'],
   ['A 47-year-old has pain down the back of the leg to the outer heel. She cannot stand on tiptoe on that side and the ankle jerk is absent.','S1','Plantar flexion, the ankle reflex and the outer heel and little toe are S1.'],
   ['A 70-year-old has a band of shingles rash running around the body at the level of the belly button.','T10','The umbilicus is the T10 dermatome.'],
   ['A 66-year-old has burning pain wrapping around the chest at the level of the nipples.','T4','The nipple line is the T4 dermatome.'],
   ['A 35-year-old has a weak, stiff shoulder after a neck injury. The arm cannot be lifted sideways and the outer shoulder is numb; reflexes are normal.','C5','Shoulder abduction and the outer shoulder are mainly C5.']]},
  {id:'fields',title:'Visual field defects',description:'Describe what the patient cannot see: place the lesion.',diagram:'field-defects',prompt:'Where is the lesion most likely?',items:[
   ['A 30-year-old woman has painful, blurred vision in her right eye only. The right pupil reacts less well when the light is swung to it.','Optic nerve','One eye plus a relative afferent pupil defect means the problem is before the chiasm.'],
   ['A 72-year-old woke unable to see anything from his left eye; the right eye is normal.','Optic nerve','Loss confined to one eye puts the lesion in that eye or its optic nerve.'],
   ['A 45-year-old keeps bumping into door frames on both sides. Testing shows she has lost the outer half of the field in each eye.','Optic chiasm','The crossing fibres from both nasal retinas meet at the chiasm, so both temporal fields go.'],
   ['A 58-year-old has lost the right half of vision in both eyes, but the shape of the loss differs between the eyes and the right pupil is subtly sluggish.','Optic tract','A homonymous loss that is incongruous, with an afferent pupil sign, points to the optic tract.'],
   ['After surgery on his left temporal lobe a 40-year-old has lost the upper right quarter of vision in both eyes.','Temporal lobe (Meyer loop)','The lower fibres (Meyer loop) loop through the temporal lobe and carry the upper field.'],
   ['After a right parietal stroke a 66-year-old has lost the lower left quarter of vision in both eyes.','Parietal optic radiation','The upper radiation fibres run through the parietal lobe and carry the lower field.'],
   ['A 75-year-old has lost the left half of vision in both eyes, identical in each eye, but can still read the central letters.','Occipital cortex','A congruous hemianopia with macular sparing is classic for occipital cortex.']]},
  {id:'aphasia',title:'Aphasia types',description:'Listen to how the patient speaks: name the aphasia.',diagram:'aphasia-tree',prompt:'Which aphasia fits best?',items:[
   ['After a stroke a 62-year-old speaks in slow, effortful, short phrases. He follows commands well but cannot repeat a sentence.','Broca aphasia','Non-fluent, good understanding, poor repetition.'],
   ['A 70-year-old barely starts speaking and says little, yet follows commands and repeats long sentences perfectly.','Transcortical motor aphasia','Like Broca aphasia, but repetition is preserved.'],
   ['A 68-year-old after a large left stroke says almost nothing, follows no commands and cannot repeat.','Global aphasia','Every language function is lost.'],
   ['A 74-year-old says little and understands little, but echoes back whatever you say word for word.','Mixed transcortical aphasia','Repetition is the only function left.'],
   ['A 58-year-old speaks fluently and understands well, but repeating a sentence produces garbled sound errors.','Conduction aphasia','Fluent, good understanding, poor repetition.'],
   ['A 65-year-old speaks fluently, understands and repeats, but keeps pausing to hunt for names of objects.','Anomic aphasia','Only word finding is affected.'],
   ['A 71-year-old talks rapidly in jumbled, meaningless sentences, does not follow commands and cannot repeat. He seems unaware of the problem.','Wernicke aphasia','Fluent, poor understanding, poor repetition.'],
   ['A 76-year-old speaks fluently but makes no sense of what is said to him, yet repeats your sentences accurately.','Transcortical sensory aphasia','Like Wernicke aphasia, but repetition is preserved.']]},
  {id:'eyes',title:'Eye muscles',description:'Double vision cases: name the weak eye muscle.',diagram:'eye-muscles',prompt:'Which eye muscle is weak?',items:[
   ['A 60-year-old with diabetes sees double when looking to the right. His right eye will not turn outward.','Lateral rectus (VI)','Turning the eye outward (abduction) is the lateral rectus, supplied by the sixth nerve.'],
   ['A 55-year-old sees double looking left; her right eye will not move inward toward the nose. Her pupil and eyelid are normal.','Medial rectus (III)','Turning the eye inward (adduction) is the medial rectus.'],
   ['After a head injury a 25-year-old sees double reading and walking downstairs, and tilts his head to the opposite side. His eye cannot look down when turned in.','Superior oblique (IV)','The superior oblique depresses the eye best when it is turned in; the fourth nerve is easily hurt by head trauma.'],
   ['A 50-year-old\'s left eye cannot look up when turned toward the nose.','Inferior oblique (III)','In adduction, elevation is done by the inferior oblique.'],
   ['A 45-year-old\'s right eye cannot look up when turned outward.','Superior rectus (III)','In abduction, elevation is done by the superior rectus.'],
   ['A 48-year-old\'s left eye cannot look down when turned outward.','Inferior rectus (III)','In abduction, depression is done by the inferior rectus.']]},
  {id:'brainstem',title:'Brainstem syndromes',description:'Crossed signs at the bedside: find the level and side.',diagram:'brainstem-rule',prompt:'Where is the lesion most likely?',items:[
   ['A 66-year-old has a droopy right eyelid, a large right pupil and an eye turned down and out. His left arm and leg are weak.','Medial midbrain','A third nerve palsy on one side with weakness on the other places the lesion in the medial midbrain.'],
   ['A 70-year-old cannot turn his left eye outward and has weakness of the right arm and leg.','Medial pons','A sixth nerve palsy on one side with crossed weakness places the lesion in the medial pons.'],
   ['A 63-year-old\'s tongue points to the left when stuck out. Her right arm and leg are weak and she cannot feel vibration on the right.','Medial medulla','Twelfth nerve on one side, plus the crossed pyramid and medial lemniscus, is the medial medulla.'],
   ['A 58-year-old has sudden vertigo, hoarseness and trouble swallowing. The left face has lost pain feeling and the left pupil is small, while pain is lost over the right body.','Lateral medulla','Crossed pain loss with Horner syndrome and hoarseness is the lateral medullary (Wallenberg) syndrome.'],
   ['A 61-year-old has a weak left face, deafness in the left ear, a clumsy left arm and loss of pain sensation over the right body.','Lateral pons','Facial weakness, hearing loss and ataxia on one side with crossed pain loss point to the lateral pons.']]},
  {id:'nerves',title:'Arm and leg nerves',description:'Weakness and numbness in a limb: name the nerve.',diagram:'lumbosacral',prompt:'Which nerve is most likely affected?',items:[
   ['A 30-year-old fell asleep drunk with his arm over a chair. He wakes with a wrist drop and a numb patch on the back of the hand near the thumb. His triceps works.','Radial nerve','Wrist drop with sensory loss on the back of the first web space is the radial nerve at the arm.'],
   ['A 52-year-old typist has numb thumb, index and middle fingers that wake her at night, and weakness lifting her thumb away from the palm.','Median nerve','Night numbness of the first three fingers with weak thumb abduction is carpal tunnel (median nerve).'],
   ['A 45-year-old who leans on his elbows has a numb little finger and half of the ring finger, and cannot spread his fingers.','Ulnar nerve','The ulnar nerve supplies the little finger, half the ring finger and the finger-spreading muscles.'],
   ['After a shoulder dislocation a 22-year-old cannot lift his arm out to the side and has a numb patch over the outer shoulder.','Axillary nerve','The axillary nerve supplies the deltoid and the skin over it.'],
   ['After heavy lifting a 35-year-old has weak elbow bending and numbness along the outer forearm.','Musculocutaneous nerve','It supplies the biceps and ends as the lateral cutaneous nerve of the forearm.'],
   ['A 40-year-old who sits with his legs crossed now has a foot drop and cannot turn his foot outward, but can still turn it inward.','Common fibular nerve','Foot drop with weak eversion and spared inversion localizes to the fibular nerve at the fibular head, not L5.'],
   ['After pelvic surgery a 55-year-old has a buckling knee, an absent knee jerk and a numb inner shin, but can still squeeze the thighs together.','Femoral nerve','Weak knee extension with spared hip adduction separates the femoral nerve from an L3–L4 root.'],
   ['After a difficult childbirth a 29-year-old cannot bring her leg inward and has numbness over the inner thigh.','Obturator nerve','The obturator nerve supplies the hip adductors and the inner thigh.'],
   ['A 60-year-old cannot stand on tiptoe on one side and has a numb sole; the ankle jerk is reduced but the back is pain free.','Tibial nerve','The tibial nerve supplies plantar flexion and the sole.']]}
 ],
 finder: {
  levels: [
   {id:'cortex',title:'Cerebral cortex',topic:'cortex',diagram:'cortex',test:'Look for language, neglect, field or cortical sensory signs that subcortical lesions rarely produce alone.'},
   {id:'deep',title:'Deep hemisphere (capsule, thalamus)',topic:'subcortex',diagram:'compact',test:'A dense face–arm–leg pattern without cortical signs favors compact deep pathways.'},
   {id:'brainstem',title:'Brainstem',topic:'brainstem',diagram:'brainstem-rule',test:'A cranial nerve or gaze sign sets the level; look for crossed sensory or limb findings.'},
   {id:'cord',title:'Spinal cord',topic:'cord',diagram:'cord-syndromes',test:'Search for a sensory level, bilateral long-tract signs and sphincter change; the face is spared.'},
   {id:'root',title:'Nerve root',topic:'roots',diagram:'root-signatures',test:'Compare muscles that share a root but use different nerves, and check the matching reflex.'},
   {id:'plexus',title:'Plexus',topic:'plexus',diagram:'brachial-plexus',test:'Deficits span several nerves and more than one root within one limb.'},
   {id:'nerve',title:'Single peripheral nerve',topic:'nerves',diagram:'peripheral',test:'Weakness and sensory loss map onto one named nerve and its branches.'},
   {id:'poly',title:'Polyneuropathy',topic:'nerves',diagram:'body-patterns',test:'Distal, symmetric, length-dependent findings with reduced ankle reflexes.'},
   {id:'nmj',title:'Neuromuscular junction',topic:'nmj',diagram:'nmj-compare',test:'Fatigable weakness with eye or bulbar involvement and normal sensation.'},
   {id:'muscle',title:'Muscle',topic:'muscle',diagram:'motor-unit',test:'Symmetric proximal weakness, normal sensation, reflexes preserved until late.'},
   {id:'cerebellum',title:'Cerebellum and its connections',topic:'cerebellum',diagram:'coordination',test:'Ataxia with preserved strength and position sense; check eye movements.'}
  ],
  groups: ['Motor','Sensory','Other clues'],
  findings: [
   {id:'umn',group:'Motor',label:'Brisk reflexes, spasticity or an extensor plantar',w:{cortex:2,deep:2,brainstem:2,cord:2,root:-3,plexus:-3,nerve:-3,poly:-3,nmj:-3,muscle:-3,cerebellum:-1}},
   {id:'lmn',group:'Motor',label:'Reduced reflexes, wasting or fasciculation in weak muscles',w:{root:2,plexus:2,nerve:2,poly:2,cord:1,cortex:-2,deep:-2,brainstem:-1,cerebellum:-1}},
   {id:'hemi',group:'Motor',label:'Face, arm and leg weak on the same side',w:{cortex:2,deep:3,brainstem:1,cord:-3,root:-3,plexus:-3,nerve:-3,poly:-3,nmj:-2,muscle:-3,cerebellum:-2}},
   {id:'para',group:'Motor',label:'Both legs weak, arms spared',w:{cord:3,root:1,deep:-1,brainstem:-1,nerve:-3,plexus:-2,nmj:-1,cerebellum:-2}},
   {id:'proximal',group:'Motor',label:'Symmetric proximal weakness (shoulders, hips)',w:{muscle:3,nmj:2,poly:-1,nerve:-3,root:-2,plexus:-2,cortex:-3,deep:-3,brainstem:-2,cerebellum:-3}},
   {id:'fatigue',group:'Motor',label:'Fatigable weakness, fluctuating ptosis or double vision',w:{nmj:4,brainstem:1,cortex:-2,deep:-2,cord:-2,root:-2,plexus:-2,nerve:-1,poly:-1,cerebellum:-2}},
   {id:'limb',group:'Motor',label:'Weakness across several nerves in one limb',w:{plexus:3,root:1,nerve:-1,brainstem:-1,poly:-2,nmj:-2,muscle:-2,cerebellum:-2}},
   {id:'single',group:'Motor',label:'Weakness and numbness in one named nerve territory',w:{nerve:4,root:1,poly:-1,cortex:-2,deep:-2,brainstem:-2,cord:-2,nmj:-3,muscle:-3,cerebellum:-3}},
   {id:'cortical',group:'Sensory',label:'Aphasia, neglect or impaired stereognosis with intact primary sensation',w:{cortex:4,deep:1,brainstem:-2,cord:-3,root:-3,plexus:-3,nerve:-3,poly:-3,nmj:-3,muscle:-3,cerebellum:-3}},
   {id:'field',group:'Sensory',label:'Homonymous visual field defect',w:{cortex:2,deep:2,brainstem:-2,cord:-3,root:-3,plexus:-3,nerve:-3,poly:-3,nmj:-3,muscle:-3,cerebellum:-3}},
   {id:'crossed',group:'Sensory',label:'Face affected on one side, body on the other',w:{brainstem:4,cortex:-3,deep:-3,cord:-3,root:-3,plexus:-3,nerve:-3,poly:-3,nmj:-3,muscle:-3,cerebellum:-3}},
   {id:'level',group:'Sensory',label:'A sensory level on the trunk',w:{cord:4,root:-1,poly:-2,cortex:-3,deep:-3,brainstem:-3,plexus:-3,nerve:-3,nmj:-3,muscle:-3,cerebellum:-3}},
   {id:'dissociated',group:'Sensory',label:'Pain loss on one side, vibration loss on the other',w:{cord:3,brainstem:2,cortex:-3,deep:-3,root:-3,plexus:-3,nerve:-3,poly:-3,nmj:-3,muscle:-3,cerebellum:-3}},
   {id:'dermatomal',group:'Sensory',label:'Radiating limb pain or a dermatomal strip of numbness',w:{root:4,plexus:1,nerve:1,cortex:-2,deep:-2,brainstem:-2,poly:-2,nmj:-2,muscle:-2,cerebellum:-2}},
   {id:'stocking',group:'Sensory',label:'Distal symmetric stocking-and-glove sensory loss',w:{poly:4,root:-1,cortex:-2,deep:-2,brainstem:-2,plexus:-2,nerve:-2,nmj:-2,muscle:-2,cerebellum:-2}},
   {id:'nosensory',group:'Sensory',label:'Sensation entirely normal',w:{muscle:2,nmj:2,cerebellum:1,brainstem:-1,cord:-1,root:-1,plexus:-2,nerve:-2,poly:-3}},
   {id:'cranial',group:'Other clues',label:'Cranial nerve or gaze palsy with opposite-side limb signs',w:{brainstem:4,cortex:-3,deep:-3,cord:-3,root:-3,plexus:-3,nerve:-3,poly:-3,nmj:-3,muscle:-3,cerebellum:-2}},
   {id:'ataxia',group:'Other clues',label:'Same-side limb ataxia with normal strength and position sense',w:{cerebellum:4,brainstem:2,cortex:-2,cord:-2,root:-2,plexus:-2,nerve:-2,poly:-2,nmj:-2,muscle:-2}},
   {id:'sphincter',group:'Other clues',label:'Early bladder or bowel change with leg signs',w:{cord:3,root:1,deep:-2,brainstem:-2,plexus:-2,nerve:-2,poly:-2,nmj:-2,muscle:-2,cerebellum:-2}},
   {id:'bulbar',group:'Other clues',label:'Weak swallowing or slurred, weak articulation',w:{brainstem:2,nmj:2,muscle:1,cord:-2,root:-3,plexus:-3,nerve:-2,poly:-1,cerebellum:-1}}
  ]
 }
};
