'use strict';
/* NeuroLocalize 1.8: reading guides for every atlas figure.
   view = how the figure is oriented, keys = what each labelled element means,
   use = how to apply it at the bedside, limits = what the schematic leaves out. */
window.NL_FIGGUIDE = {
 neuraxis: {view: 'A lateral brain continues down into the brainstem and spinal cord; one root, a plexus, a nerve and a muscle branch off below. Teal numbers 1–4 are central levels and gold numbers 5–8 are peripheral levels.',
  keys: ['1 Cortex: language, neglect, field cuts and cortical sensory loss are the giveaways.', '2 Deep hemisphere: dense, even face–arm–leg weakness without cortical signs.', '3 Brainstem: a cranial nerve sign with crossed limb findings.', '4 Spinal cord: a sensory level, both sides, sphincter change, face spared.', '5 Root: pain and deficit in one dermatome and myotome.', '6 Plexus: several nerves and roots in one limb.', '7 Nerve: one named nerve territory.', '8 Junction or muscle: weakness with no sensory loss at all.'],
  use: 'Read the list from top to bottom and stop at the first level that explains every finding; then look for one finding that would argue against it.',
  limits: 'Levels can be involved together (for example cord and roots), and the drawing is not to scale.'},
 motor: {view: 'A coronal section of both hemispheres seen from behind, so the patient\'s left is on the left, above the brainstem and cervical cord. One teal pathway runs from the left motor cortex to the right arm.',
  keys: ['Left motor cortex: the pathway starts near the top of the left hemisphere.', 'Internal capsule: the fibres pass between thalamus and lentiform nucleus.', 'Pyramidal decussation: most fibres cross in the caudal medulla.', 'Lateral corticospinal tract: after crossing, the fibres descend on the right side of the cord.', 'Anterior horn: the fibres end on lower motor neurons that drive the right arm.'],
  use: 'Mark the lesion on the pathway. Above the decussation, limb weakness is on the opposite side; in the cord below it, weakness is on the same side as the lesion.',
  limits: 'Only the main lateral corticospinal route is shown; facial (corticobulbar) and uncrossed fibres are omitted.'},
 cortex: {view: 'The left hemisphere seen from the side, front to the left, with the cerebellum and brainstem below. Coloured areas are approximate.',
  keys: ['Primary motor cortex (teal strip in front of the central sulcus): opposite face, arm and leg.', 'Primary sensory cortex (blue strip behind it): opposite-side discriminative sensation.', 'Broca area (gold, inferior frontal): expressive language, usually left.', 'Wernicke area (gold, posterior temporal): comprehension, usually left; the dashed arcuate links join the two.', 'Parietal association cortex (purple): attention and praxis; neglect when on the right.', 'Visual cortex (red, occipital pole): the opposite half of the visual field.'],
  use: 'Match the cortical sign to its area, then use the side of the body or field affected to decide which hemisphere.',
  limits: 'Functions depend on networks, boundaries vary, and language is on the right in a minority of people.'},
 compact: {view: 'A horizontal (axial) slice through one hemisphere, front at the top and midline on the right.',
  keys: ['Caudate and lateral ventricle (top, near the midline).', 'Lentiform nucleus (wedge, lateral): putamen and globus pallidus.', 'Thalamus (oval, posterior and medial).', 'Anterior limb of the internal capsule: frontal–pontine and thalamic fibres.', 'Genu (gold): corticobulbar fibres for the face and tongue.', 'Posterior limb (teal): corticospinal fibres, arm then leg.', 'Thalamocortical sensory fibres (blue) and the retrolenticular optic radiation (red).'],
  use: 'A small lesion where these fibres are packed tightly can weaken the face, arm and leg equally, without cortical signs. Add sensory loss or a field cut if the lesion reaches the blue or red fibres.',
  limits: 'Fibre positions are approximate and overlap; a pure motor stroke can also come from the ventral pons.'},
 crossed: {view: 'A cross-section of the open (upper) medulla, dorsal side up. The red dashed area is a left lateral lesion.',
  keys: ['Spinal trigeminal nucleus (blue): same-side facial pain and temperature.', 'Spinothalamic tract (red): pain and temperature from the opposite body, already crossed in the cord.', 'Nucleus ambiguus: hoarseness and swallowing difficulty.', 'Sympathetic fibres: same-side Horner syndrome.', 'Inferior cerebellar peduncle: same-side limb ataxia.', 'Medial lemniscus, pyramid and olive (spared): why strength and vibration are normal.'],
  use: 'Crossed pain loss (face on one side, body on the other) places the lesion in the lateral lower brainstem; the facial side marks the lesion side.',
  limits: 'Real lateral medullary lesions are often incomplete, and the exact arrangement varies along the medulla.'},
 cranial: {view: 'The brainstem from the front. Nerves are labelled on the left; stubs on the right show the same exits. Brackets group the nerves by level.',
  keys: ['Midbrain: III emerges between the cerebral peduncles; IV leaves the back of the midbrain and wraps forward.', 'Pons: V leaves the side of the pons; VI, VII and VIII emerge at the junction with the medulla.', 'Medulla: IX, X and XI leave behind the olive; XII leaves between the pyramid and olive.', 'XI also has roots from the upper cervical cord (dashed).'],
  use: 'The cranial nerve involved sets the level; then look for limb, sensory or gaze signs to decide between a brainstem lesion and a lesion along the nerve.',
  limits: 'Nuclei lie inside the brainstem, often at different levels from where the nerves leave; this view shows exits only.'},
 hemicord: {view: 'An axial slice of the spinal cord at one level, dorsal side up. The left half is damaged.',
  keys: ['Dorsal column (gold, back): vibration and position from the same side; it crosses later, in the medulla.', 'Lateral corticospinal tract (teal, side): already crossed; damage weakens the same side below the lesion.', 'Anterolateral (spinothalamic) tract (blue, front and side): pain and temperature from the other side, which crossed near entry.'],
  use: 'After a one-sided cord lesion, look for same-side weakness and vibration loss with opposite-side pain and temperature loss below the level.',
  limits: 'Pain loss usually begins a segment or two below the lesion, and real lesions are rarely an exact half.'},
 peripheral: {view: 'A spinal cord with five colour-coded roots. Their fibres mix in the plexus and leave as three nerves, each going to a muscle.',
  keys: ['Each colour is one root, so you can follow its fibres into more than one nerve.', 'Nerve A carries roots 1–3, nerve B roots 2–4 and nerve C roots 3–5.', 'Root 3 reaches all three muscles.'],
  use: 'A root lesion causes partial weakness in several muscles that use different nerves (a myotome). A nerve lesion weakens one muscle group fully, with that nerve\'s sensory area. Compare muscles that share a root but not a nerve.',
  limits: 'Illustrative wiring only; the real brachial and lumbosacral plexuses are drawn in figures 24 and 34.'},
 'motor-unit': {view: 'A magnified view of one motor end-plate: the nerve terminal above, the muscle fibre below, the synaptic cleft between.',
  keys: ['Myelinated axon and Schwann cell: the motor nerve arriving.', 'Vesicles (gold): store acetylcholine.', 'Calcium channels (blue) at active zones: trigger release.', 'Synaptic cleft: acetylcholine crosses here.', 'Acetylcholine receptors (teal) on the crests of the junctional folds.', 'Muscle fibre with striations: the effector.'],
  use: 'Name which side fails: presynaptic release (Lambert–Eaton), postsynaptic receptors (myasthenia) or the muscle itself (myopathy). Each gives a different bedside pattern.',
  limits: 'Not to scale; real end-plates contain far more vesicles and receptors.'},
 coordination: {view: 'The cerebellum seen from behind, brainstem above. The midline vermis is gold; the hemispheres are teal.',
  keys: ['Vermis (midline): posture, stance and gait; damage causes truncal sway and a broad-based gait.', 'Hemisphere: coordination of the limbs on the same side; damage causes dysmetria, intention tremor and dysdiadochokinesia.'],
  use: 'Truncal and gait ataxia with normal limbs points to the midline; one-sided limb ataxia points to the hemisphere on the same side. Always check position sense to exclude sensory ataxia.',
  limits: 'The flocculus and cerebellar connections in the brainstem can also cause ataxia and are not shown.'},
 vision: {view: 'The visual pathway seen from above inside an outline of the brain. Gold fibres carry the left half of the visual field; blue fibres carry the right half.',
  keys: ['Optic nerve: one eye only.', 'Optic chiasm: nasal retinal fibres cross; temporal fibres stay on the same side.', 'Optic tract and lateral geniculate (LGN): from here on, each side carries the opposite half-field from both eyes.', 'Meyer loop (temporal lobe): the upper quadrant of the field.', 'Parietal fibres: the lower quadrant.', 'Visual cortex: the opposite half-field, often with central sparing.'],
  use: 'A defect in one eye is in front of the chiasm; bitemporal loss is the chiasm; the same half missing in both eyes (homonymous) is behind it, on the opposite side.',
  limits: 'Pupillary fibres and the detailed spread of the radiations are simplified.'},
 'umn-lmn': {view: 'A motor pathway column (cortex to muscle) beside a comparison table.',
  keys: ['Upper motor neuron (teal): cortex down to the anterior horn.', 'Lower motor neuron (gold): anterior horn cell, root, nerve and muscle.', 'Table rows: tone, reflexes, plantar response, wasting, fasciculation and distribution of weakness.'],
  use: 'Sort the weakness first: upper motor neuron signs mean brain, brainstem or cord; lower motor neuron signs mean anterior horn, root, plexus or nerve.',
  limits: 'Acute central lesions can be flaccid, and mixed signs occur with cord lesions and motor neuron disease.'},
 'body-patterns': {view: 'Six front-facing figures, shaded where findings cluster.',
  keys: ['One side from face to leg: hemisphere or brainstem.', 'Face one side, body the other: brainstem.', 'Everything below a line: spinal cord.', 'A strip in one limb: root or named nerve.', 'Hands and feet: length-dependent polyneuropathy.', 'Shoulders and hips: muscle or junction (motor only).'],
  use: 'Sketch the patient\'s deficit and compare it with the six shapes before choosing tests.',
  limits: 'Shading shows typical patterns, not exact borders.'},
 'aphasia-tree': {view: 'A decision tree read from the top: fluency, then comprehension, then repetition.',
  keys: ['Shaded leaves (repetition impaired): Broca, global, conduction and Wernicke, the perisylvian aphasias.', 'White leaves (repetition preserved): transcortical motor, mixed, sensory and anomic.', 'TC means transcortical.'],
  use: 'Test fluency, comprehension and repetition in that order and follow the branches; the leaf names the classic syndrome and its usual region.',
  limits: 'Real aphasias are often mixed and change over time.'},
 vascular: {view: 'Lateral and medial views of one hemisphere, front to the left, shaded by arterial territory.',
  keys: ['Middle cerebral (teal): most of the lateral surface; face and arm more than leg, language or neglect.', 'Anterior cerebral (gold): medial frontal and parietal surface; leg more than arm.', 'Posterior cerebral (blue): occipital and inferior temporal lobes; opposite homonymous hemianopia.'],
  use: 'Match the distribution of deficits to a territory: leg-predominant suggests the anterior cerebral, face–arm with language or neglect the middle cerebral, an isolated field cut the posterior cerebral.',
  limits: 'Territories vary between people, and watershed zones lie between them.'},
 'field-defects': {view: 'The visual pathway from above (patient\'s left on the left) with six numbered lesion sites, and the field each removes shown as left and right eye charts.',
  keys: ['1 Optic nerve: one eye.', '2 Chiasm: bitemporal hemianopia.', '3 Optic tract: opposite homonymous hemianopia, often incongruous.', '4 Meyer loop: opposite upper quadrant.', '5 Parietal radiation: opposite lower quadrant.', '6 Occipital cortex: opposite hemianopia, often with central sparing.'],
  use: 'Plot the patient\'s field defect, find the matching chart, and read off the lesion site.',
  limits: 'Partial lesions give partial versions of these patterns.'},
 'brainstem-rule': {view: 'A brainstem outline with a shaded medial strip, beside lists of medial and lateral structures.',
  keys: ['Four medial "M" structures: motor pathway, medial lemniscus, MLF, motor nuclei III, IV, VI, XII.', 'Four lateral "S" structures: spinocerebellar links, spinothalamic tract, sensory nucleus of V, sympathetic fibres.', 'Level: III–IV midbrain, V–VIII pons, IX–XII medulla.'],
  use: 'Decide medial or lateral from the long-tract signs, then the level from the cranial nerve involved.',
  limits: 'A memory aid; trochlear fibres cross and real lesions overlap.'},
 'gaze-circuit': {view: 'Both eyes above a brainstem schematic, showing how the right pons drives rightward gaze.',
  keys: ['PPRF: starts horizontal saccades.', 'VI nucleus: motor neurons to the same-side lateral rectus and interneurons to the opposite MLF.', 'MLF: carries the signal up to the opposite III nucleus for the medial rectus.', 'Red marker: an MLF lesion (internuclear ophthalmoplegia).'],
  use: 'An MLF lesion stops adduction on that side; a VI nucleus lesion causes a gaze palsy of both eyes; a VI nerve lesion stops abduction of one eye only.',
  limits: 'Vertical gaze and vestibular inputs are omitted.'},
 facial: {view: 'Two faces drawn facing you; the weak side is shaded.',
  keys: ['Central pattern: lower face weak, forehead and eye closure largely preserved.', 'Peripheral pattern: the whole half of the face weak, including the forehead, with a lower brow and flattened fold beside the mouth.'],
  use: 'Check forehead wrinkling and eye closure: preserved suggests a lesion above the facial nucleus on the opposite side; weak suggests the nucleus or nerve on the same side.',
  limits: 'Forehead sparing is a strong clue but not absolute.'},
 horner: {view: 'A side view of the head and chest showing the three-neuron sympathetic chain to the eye.',
  keys: ['First order (teal): hypothalamus down the brainstem and cord to C8–T2.', 'Second order (gold): out of the cord, over the lung apex to the superior cervical ganglion.', 'Third order (blue): along the internal carotid to the pupil dilator and eyelid.'],
  use: 'A Horner syndrome (mild ptosis, small pupil) can start anywhere on this chain; the company it keeps (brainstem signs, a lung apex lesion, neck pain) tells you where.',
  limits: 'Sweating loss depends on the site and is simplified here.'},
 'cord-syndromes': {view: 'Five axial cord slices, dorsal side up, with roots shown; red shading marks the damage.',
  keys: ['Complete: all modalities lost below the level.', 'Central: arms worse than legs; cape-like pain loss.', 'Anterior: strength and pain lost; vibration and position spared.', 'Posterior: vibration and position lost; sensory ataxia.', 'Hemicord: same-side weakness and vibration loss, opposite-side pain loss.'],
  use: 'Work out which modalities are lost and on which side, then match the shape.',
  limits: 'Patterns are idealised; real lesions are often partial.'},
 'sensory-pathways': {view: 'Two pathways from the right body to the left brain, with the midline dashed.',
  keys: ['Dorsal columns (gold): vibration, position and fine touch; ascend on the same side and cross in the medulla.', 'Spinothalamic tract (blue): pain and temperature; cross within a few segments of entry.', 'Both relay in the thalamus (VPL) before the cortex.'],
  use: 'If the two systems are lost on different sides, the lesion is in the cord; if both are lost on the same side, it is above the medulla.',
  limits: 'Light touch travels in both systems and is a poor discriminator.'},
 'root-signatures': {view: 'A table of seven commonly tested roots.',
  keys: ['For each root: the main movement, the reflex if one exists, and the sensory area.', 'C5–C8 in the arm, L4, L5 and S1 in the leg.'],
  use: 'Test one movement, one reflex and one sensory point per root, and compare muscles that share a root but use different nerves.',
  limits: 'Territories overlap and vary between people.'},
 'brachial-plexus': {view: 'The brachial plexus in five columns from roots to terminal nerves. Teal lines are anterior divisions; gold dashed lines are posterior divisions.',
  keys: ['Roots C5–T1 form upper, middle and lower trunks.', 'Divisions regroup into lateral, posterior and medial cords.', 'Lateral cord: musculocutaneous and part of median. Posterior cord: axillary and radial. Medial cord: ulnar and part of median.'],
  use: 'Trace the weak muscles backward to the smallest structure they share: a cord, a trunk or the roots.',
  limits: 'Small branches (suprascapular, long thoracic and others) are omitted.'},
 'nmj-compare': {view: 'Two end-plates side by side with a comparison table below.',
  keys: ['Myasthenia gravis: red crosses on postsynaptic receptors.', 'Lambert–Eaton: red crosses on presynaptic calcium channels.', 'Table: first weakness, reflexes, effect of effort, autonomic features, nerve stimulation.'],
  use: 'Fatigable eye and bulbar weakness with normal reflexes suggests myasthenia; proximal leg weakness, low reflexes that improve after effort and a dry mouth suggest Lambert–Eaton.',
  limits: 'Patterns overlap; confirm with appropriate testing.'},
 'weakness-flow': {view: 'A flowchart starting from weakness.',
  keys: ['First question: upper motor neuron signs?', 'If yes: is the face weak too? Yes points to brain or brainstem; no to the spinal cord.', 'If no: is there sensory loss? Yes points to root, plexus or nerve; no to junction, muscle or motor neuron.'],
  use: 'Use it as a first sort, then refine with the region-specific figures.',
  limits: 'Mixed upper and lower motor neuron signs need the note at the bottom.'},
 'time-course': {view: 'Four panels plotting severity against time.',
  keys: ['Sudden step: vascular, seizure or trauma.', 'Rise over hours to weeks: inflammatory, infectious, toxic-metabolic or demyelinating.', 'Slow climb over months to years: degenerative, neoplastic or genetic.', 'Repeated attacks: episodic or relapsing disorders.'],
  use: 'After localizing, use the time course to rank possible mechanisms.',
  limits: 'These are tendencies with many exceptions.'},
 'reflex-arc': {view: 'A muscle on the left and a spinal cord section on the right, linked by the reflex arc, with descending control from above.',
  keys: ['1 Sensory fibre or ganglion: reflex reduced or lost.', '2 Anterior horn or motor root: reduced, with wasting.', '3 Peripheral nerve: reduced in its territory.', '4 Descending pathway: reflexes brisk and spreading.', 'Pills: biceps C5–C6, brachioradialis C6, triceps C7, knee L3–L4, ankle S1.'],
  use: 'Reduced reflexes mean the lesion is in the arc; brisk reflexes mean it is above it.',
  limits: 'Reflexes vary between people; compare sides.'},
 'eye-muscles': {view: 'The right eye as you face the patient, with six arrows in an H pattern; abduction points to your left.',
  keys: ['Lateral rectus (VI): abducts.', 'Medial rectus (III): adducts.', 'Superior and inferior rectus (III): elevate and depress best in abduction.', 'Inferior oblique (III) and superior oblique (IV): elevate and depress best in adduction.'],
  use: 'Find the direction in which double vision is worst, identify the muscle acting in that direction, then its nerve.',
  limits: 'Muscle actions are simplified to their main test positions.'},
 'pupil-reflex': {view: 'Both eyes from above with the light reflex pathway through the midbrain.',
  keys: ['Afferent (gold): optic nerve and tract to the pretectal nuclei.', 'Pretectal nuclei project to both Edinger–Westphal nuclei.', 'Efferent (teal): parasympathetic fibres in III via the ciliary ganglion to each pupil.'],
  use: 'An afferent defect shows on the swinging light test with equal pupils at rest; an efferent (III) defect gives one large pupil that reacts poorly whichever eye is lit.',
  limits: 'The near response and sympathetic pathway are not shown.'},
 'cavernous-sinus': {view: 'A coronal slice through both cavernous sinuses either side of the pituitary, above the sphenoid sinus.',
  keys: ['Lateral wall: III, IV, V1 and V2.', 'Within the sinus: the internal carotid artery with VI beside it.'],
  use: 'Several of these nerves on one side, sometimes with a Horner syndrome, suggests the cavernous sinus; add optic nerve involvement and the orbital apex becomes more likely.',
  limits: 'Positions are simplified and vary along the sinus.'},
 'hand-nerves': {view: 'Palm and back views of a right hand shaded by sensory nerve.',
  keys: ['Median (teal): palm side of thumb, index, middle and half the ring finger; dorsal fingertips.', 'Ulnar (gold): little finger and the ulnar half of the ring finger, front and back.', 'Radial (blue): back of the radial hand, especially the first web space.'],
  use: 'Map the numb area: a split ring finger points to a nerve rather than the C8 root.',
  limits: 'Borders vary, especially on the back of the hand.'},
 'dermatome-landmarks': {view: 'A front-view figure with thirteen standard sensory test points and a key.',
  keys: ['C5 lateral elbow crease, C6 thumb, C7 middle finger, C8 little finger, T1 medial elbow crease.', 'T4 nipple line, T10 umbilicus.', 'L1 groin, L2 front of mid-thigh, L3 medial knee, L4 medial ankle, L5 top of foot, S1 outer heel.'],
  use: 'Test these points to find a sensory level on the trunk or a single root in a limb.',
  limits: 'Neighbouring dermatomes overlap a lot.'},
 lumbosacral: {view: 'Lumbosacral roots on the left, their main nerves, the sciatic branches, and a foot-drop table.',
  keys: ['Femoral (L2–L4): knee extension and knee reflex.', 'Obturator (L2–L4): hip adduction.', 'Superior gluteal (L4–S1): hip abduction.', 'Sciatic (L4–S3) dividing into tibial and common fibular.', 'Table: inversion and hip abduction separate L5 from a fibular lesion.'],
  use: 'In foot drop, test inversion and hip abduction; in thigh weakness, compare knee extension with hip adduction.',
  limits: 'Small branches and the pudendal nerve are omitted.'},
 'conus-cauda': {view: 'A side view of the lower spine showing the cord ending near L1–L2, with roots below, beside a comparison table.',
  keys: ['Conus: often sudden, bilateral and symmetric, early saddle and sphincter change, mixed upper and lower motor neuron signs.', 'Cauda equina: often gradual and asymmetric, prominent root pain, lower motor neuron signs only.'],
  use: 'Use the table to lean toward one site, but treat new saddle numbness or sphincter change as urgent either way.',
  limits: 'Many lesions overlap both patterns.'}
};
